"""Data layer for the dashboard API.

Shares one Postgres database with the voice agent (the agent writes call
rows; this module reads them and owns every other dashboard table) via
DATABASE_URL. Was SQLite through early development; moved to Postgres for
the durability/concurrency a sellable multi-tenant product needs (single-
writer lock, no replication, no failover — see
vistrow-voice-infrastructure-requirements.txt). dbconn.py is a thin shim
that keeps every call site below in its original sqlite3-flavored form
(`?` placeholders, `conn.execute(...)`, `with conn:` committing without
closing, `cursor.lastrowid`).

Lives in server/ rather than importing agent.db because agent's package
pulls in livekit-agents, which isn't installed in this venv; dbconn.py is
duplicated into agent/ instead so both stay independently importable.
"""

import csv
import hashlib
import io
import json
import secrets
import time

import dbconn

# Every created_at/updated_at default below reproduces SQLite's
# datetime('now') output exactly ("YYYY-MM-DD HH:MM:SS", UTC, no fractional
# seconds) as a TEXT column — verified against a live Postgres instance —
# so every existing call site, the frontend's date parsing, and old SQLite-
# era row data all keep working unchanged; this is a storage-engine swap,
# not a schema redesign.
_NOW = "(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))"

_SCHEMA = f"""
CREATE TABLE IF NOT EXISTS calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    room_name TEXT NOT NULL,
    visitor_identity TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    duration_seconds REAL,
    reply_language TEXT,
    lead_name TEXT,
    lead_phone TEXT,
    lead_budget TEXT,
    lead_location TEXT,
    lead_timeline TEXT,
    lead_company TEXT,
    lead_use_case TEXT,
    lead_team_size TEXT,
    site_visit_json TEXT,
    transcript_json TEXT NOT NULL,
    call_type TEXT DEFAULT 'browser',
    site_id INTEGER,
    agent_id INTEGER
);

CREATE TABLE IF NOT EXISTS sites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    name TEXT NOT NULL,
    site_key TEXT NOT NULL UNIQUE,
    allowed_domain TEXT DEFAULT '',
    agent_id INTEGER,
    status TEXT DEFAULT 'active',
    widget_position TEXT DEFAULT 'bottom-right',
    widget_label TEXT DEFAULT 'Talk to us',
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    plan TEXT DEFAULT 'starter',
    -- True for exactly one account platform-wide: the operator's own
    -- account, allowed to flag an agent as agents.is_platform_demo. Every
    -- other tenant's agents table has the same column, but only this
    -- account may set it — see is_platform_owner() / update_agent below.
    is_platform_owner INTEGER DEFAULT 0,
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'owner',
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS agents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    model TEXT DEFAULT 'gpt-4.1',
    voice TEXT DEFAULT 'pooja',
    language TEXT DEFAULT 'hi-IN',
    status TEXT DEFAULT 'live',
    system_prompt TEXT DEFAULT '',
    kb_id INTEGER,
    tone TEXT DEFAULT 'balanced',
    -- At most one agent platform-wide is flagged true — the public marketing
    -- site's /demo and /call routes have no per-tenant identity to route by,
    -- so this names which agent answers them (see agent/db.py get_agent_config).
    is_platform_demo INTEGER DEFAULT 0,
    -- Conversation-start behavior. first_speaker is 'agent' (AI greets first)
    -- or 'user' (agent waits). welcome_message, when set, is the exact opening
    -- line the agent speaks; blank means it generates a greeting from the prompt.
    first_speaker TEXT DEFAULT 'agent',
    welcome_message TEXT DEFAULT '',
    -- Speech/turn-taking tuning. interruption_sensitivity 0-1 (higher = the
    -- agent yields the floor more readily). silence_reminder_ms>0 makes the
    -- agent re-prompt after that much caller silence, up to silence_reminder_max
    -- times; end_call_on_silence_ms>0 hangs up after that much dead air.
    interruption_sensitivity REAL DEFAULT 0.5,
    silence_reminder_ms INTEGER DEFAULT 0,
    silence_reminder_max INTEGER DEFAULT 1,
    end_call_on_silence_ms INTEGER DEFAULT 0,
    -- Hard call length ceiling in seconds; 0 = no limit.
    max_call_duration_s INTEGER DEFAULT 0,
    -- Which built-in tools this agent may call, comma-separated (empty = the
    -- default set). transfer_phone is the number the transfer_call tool dials.
    enabled_functions TEXT DEFAULT '',
    transfer_phone TEXT DEFAULT '',
    -- JSON array of operator-defined webhook tools the agent can call mid-call:
    -- [{"name","description","url","method","headers","parameters"}].
    custom_functions TEXT DEFAULT '[]',
    -- JSON array of structured fields to pull from the transcript after the
    -- call: [{"key","type","description"}].
    post_call_fields TEXT DEFAULT '[]',
    -- Per-agent webhook that receives call events/results (blank = none).
    webhook_url TEXT DEFAULT '',
    -- When 1, the agent recalls prior conversations with a returning caller
    -- (keyed by phone in caller_memory) — inbound/outbound only, not web calls.
    memory_enabled INTEGER DEFAULT 0,
    created_at TEXT DEFAULT {_NOW},
    updated_at TEXT DEFAULT {_NOW}
);

-- Per-(agent, caller) rolling memory so an agent with memory_enabled can
-- greet a returning caller with context from last time. Only phone calls
-- populate this (a web visitor has no stable identity across sessions).
CREATE TABLE IF NOT EXISTS caller_memory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    agent_id INTEGER,
    caller_phone TEXT NOT NULL,
    summary TEXT DEFAULT '',
    updated_at TEXT DEFAULT {_NOW},
    UNIQUE(agent_id, caller_phone)
);

-- Programmatic API keys, scoped to a tenant account. We store only the
-- SHA-256 of the full key (it's shown to the operator exactly once at
-- creation); prefix is the human-readable leading chunk kept for the list.
CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    name TEXT NOT NULL DEFAULT 'API key',
    prefix TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    last_used_at TEXT,
    created_at TEXT DEFAULT {_NOW}
);

-- Single-use password-reset tokens. We store only the SHA-256 of the token
-- (the raw token goes in the emailed link); expires_at is a UTC epoch second.
CREATE TABLE IF NOT EXISTS password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at BIGINT NOT NULL,
    used INTEGER DEFAULT 0,
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT DEFAULT '',
    status TEXT DEFAULT 'new',
    tags TEXT DEFAULT '',
    source TEXT DEFAULT 'manual',
    last_called_at TEXT,
    created_at TEXT DEFAULT {_NOW},
    UNIQUE(account_id, phone)
);

CREATE TABLE IF NOT EXISTS knowledge_bases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    name TEXT NOT NULL,
    strict INTEGER DEFAULT 1,
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS knowledge_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'text',
    content TEXT NOT NULL,
    created_at TEXT DEFAULT {_NOW}
);

-- Structured question/answer pairs the operator curates (and can auto-extract
-- from an uploaded brochure). Emitted to the agent as an authoritative FAQ the
-- strict-mode prompt tells it to quote verbatim instead of improvising —
-- position keeps the operator's manual ordering stable in the editor.
-- Scoped to a tenant via kb_id -> knowledge_bases.account_id (not duplicated
-- here) — every query that touches a source/qa row joins through that.
CREATE TABLE IF NOT EXISTS kb_qa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id INTEGER NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    position INTEGER DEFAULT 0,
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS inbound_routes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    phone_number TEXT,
    agent_id INTEGER,
    timezone TEXT DEFAULT 'Asia/Kolkata',
    max_concurrent INTEGER DEFAULT 1,
    start_date TEXT,
    end_date TEXT,
    window_start TEXT,
    window_end TEXT,
    active_days TEXT DEFAULT 'Mon,Tue,Wed,Thu,Fri',
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT {_NOW}
);

CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    name TEXT NOT NULL,
    agent_id INTEGER,
    contact_tag TEXT DEFAULT '',
    scheduled_date TEXT,
    window_start TEXT,
    window_end TEXT,
    status TEXT DEFAULT 'scheduled',
    created_at TEXT DEFAULT {_NOW}
);

-- Per-account copy of each well-known integration (CRM webhook, Cal.com,
-- Sheets) — composite key so two tenants' webhook URLs/config never collide.
CREATE TABLE IF NOT EXISTS integrations (
    account_id INTEGER NOT NULL,
    key TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT DEFAULT '',
    status TEXT DEFAULT 'not_connected',
    config_json TEXT DEFAULT '{{}}',
    last_sync TEXT,
    PRIMARY KEY (account_id, key)
);

CREATE TABLE IF NOT EXISTS phone_numbers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    number TEXT NOT NULL UNIQUE,
    label TEXT DEFAULT '',
    provider TEXT DEFAULT 'enablex',
    agent_id INTEGER,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT {_NOW},
    lk_trunk_id TEXT,
    lk_dispatch_rule_id TEXT
);

-- Per-account settings (billing rates, EnableX credentials, credit totals) —
-- composite key so tenant A's telephony credentials never leak to tenant B.
CREATE TABLE IF NOT EXISTS settings (
    account_id INTEGER NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    PRIMARY KEY (account_id, key)
);
"""

# EnableX Voice API. Outbound calls authenticate with HTTP Basic using
# Base64(APP_ID:APP_KEY); the App Key is a server-side secret and is never
# returned to the browser.
ENABLEX_API_BASE = "https://api.enablex.io/voice/v1"

# The one account allowed to flag an agent as the public marketing site's
# demo (agents.is_platform_demo) — see init_tables()'s bootstrap and
# is_platform_owner() below. A single hardcoded operator email is
# deliberately minimal for a still-single-operator product; generalize to a
# real admin-role system if/when there's more than one internal operator.
_PLATFORM_OWNER_EMAIL = "vistrowai@gmail.com"

_SEED_INTEGRATIONS = [
    (
        "webhook",
        "CRM webhook",
        "CRM",
        "POST every qualified lead and booked site visit to your CRM endpoint in real time.",
    ),
    (
        "calcom",
        "Cal.com",
        "Scheduling & Booking",
        "Sync booking pages so agents schedule site visits directly on your calendar.",
    ),
    (
        "sheets",
        "Google Sheets",
        "Reporting",
        "Append every completed call as a row in a shared sheet.",
    ),
]

# Same Hinglish-aware frustration cues the live agent uses for its calm-voice
# switch (agent/emotion.py) — reused here to derive a per-call sentiment badge.
_NEGATIVE_WORDS = {
    "frustrated", "frustrating", "annoyed", "annoying", "angry", "furious",
    "ridiculous", "terrible", "horrible", "worst", "useless", "pathetic",
    "waste", "complaint", "complain", "scam", "cheated", "fraud", "bakwas",
    "bekaar", "faltu", "ghatiya", "dhokha", "problem", "problems", "issue",
    "issues", "delay", "delayed", "nonsense", "stupid", "stop calling",
}
_POSITIVE_WORDS = {
    "great", "perfect", "excellent", "wonderful", "amazing", "love", "happy",
    "thanks", "thank you", "helpful", "badhiya", "accha", "acha", "shukriya",
    "dhanyavad", "sahi", "wah", "interested", "excited",
}


def _connect() -> dbconn.Conn:
    return dbconn.connect()


# Tables with a plain nullable account_id column whose pre-multi-tenant rows
# (from the SQLite era, carried over by the one-time data migration) need
# adopting by the first real account.
_BACKFILL_TABLES = ("agents", "sites", "inbound_routes", "campaigns", "phone_numbers", "calls", "knowledge_bases", "contacts")


def _backfill_legacy_account_id(conn: dbconn.Conn, account_id: int) -> None:
    """Every row left with account_id IS NULL predates multi-tenancy —
    hand them to `account_id` (the first account ever created), so existing
    data becomes that account's data rather than every tenant's data."""
    for table in _BACKFILL_TABLES:
        conn.execute(f"UPDATE {table} SET account_id = ? WHERE account_id IS NULL", (account_id,))


def provision_account_defaults(conn: dbconn.Conn, account_id: int) -> None:
    """Starter state for a brand-new (non-legacy) account: one default agent
    to test with, its own copy of the well-known integrations, and its own
    billing settings — mirrors what init_tables used to seed globally."""
    conn.execute(
        "INSERT INTO agents (account_id, name, description) VALUES (?, ?, ?)",
        (
            account_id,
            "Artha",
            "Default sales agent — qualifies leads and books appointments in 11 Indian languages.",
        ),
    )
    for key, name, category, description in _SEED_INTEGRATIONS:
        conn.execute(
            "INSERT INTO integrations (account_id, key, name, category, description) VALUES (?, ?, ?, ?, ?) "
            "ON CONFLICT (account_id, key) DO NOTHING",
            (account_id, key, name, category, description),
        )
    for key, value in (
        # Free trial allowance for a brand-new signup — deliberately small;
        # an operator upgrades the account's plan for more.
        ("credits_total", "10"),
        # Phone minutes burn more credits than browser/widget minutes — they
        # carry an EnableX telephony cost the others don't.
        ("credit_rate_browser", "1"),
        ("credit_rate_phone", "1.5"),
        ("credit_rate_widget", "1"),
    ):
        conn.execute(
            "INSERT INTO settings (account_id, key, value) VALUES (?, ?, ?) "
            "ON CONFLICT (account_id, key) DO NOTHING",
            (account_id, key, value),
        )


def init_tables() -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(_SCHEMA)
            # CREATE TABLE IF NOT EXISTS above is a no-op on a table that
            # already exists in production — new columns added after go-live
            # need an explicit migration to actually land on the live table.
            for column, coltype in (
                ("lead_company", "TEXT"),
                ("lead_use_case", "TEXT"),
                ("lead_team_size", "TEXT"),
                # JSON blob of post-call structured fields the agent extracted
                # from this call's transcript (per the agent's post_call_fields).
                ("extracted_data", "TEXT DEFAULT ''"),
            ):
                conn.execute(f"ALTER TABLE calls ADD COLUMN IF NOT EXISTS {column} {coltype}")
            conn.execute("ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_platform_demo INTEGER DEFAULT 0")
            # Agent-builder settings added after go-live — explicit migrations so
            # they land on the existing production agents table (see agents CREATE
            # TABLE above for what each one does).
            for column, coltype in (
                ("first_speaker", "TEXT DEFAULT 'agent'"),
                ("welcome_message", "TEXT DEFAULT ''"),
                ("interruption_sensitivity", "REAL DEFAULT 0.5"),
                ("silence_reminder_ms", "INTEGER DEFAULT 0"),
                ("silence_reminder_max", "INTEGER DEFAULT 1"),
                ("end_call_on_silence_ms", "INTEGER DEFAULT 0"),
                ("max_call_duration_s", "INTEGER DEFAULT 0"),
                ("enabled_functions", "TEXT DEFAULT ''"),
                ("transfer_phone", "TEXT DEFAULT ''"),
                ("custom_functions", "TEXT DEFAULT '[]'"),
                ("post_call_fields", "TEXT DEFAULT '[]'"),
                ("webhook_url", "TEXT DEFAULT ''"),
                ("memory_enabled", "INTEGER DEFAULT 0"),
            ):
                conn.execute(f"ALTER TABLE agents ADD COLUMN IF NOT EXISTS {column} {coltype}")
            conn.execute("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_platform_owner INTEGER DEFAULT 0")
            # Self-healing bootstrap: whichever account owns the platform
            # operator's own login gets is_platform_owner — runs on every
            # boot (idempotent) so it applies whether that account was
            # created before or after this migration shipped, without a
            # one-off manual production update.
            conn.execute(
                "UPDATE accounts SET is_platform_owner = 1 WHERE id = ("
                "  SELECT account_id FROM users WHERE email = ?"
                ")",
                (_PLATFORM_OWNER_EMAIL,),
            )
            # If the first account already exists (a prior boot completed a
            # signup), any row still missing account_id predates that signup
            # — hand it over now rather than waiting for create_account_with_
            # owner to run again. No-op on a fresh install with zero accounts.
            first_account = conn.execute("SELECT MIN(id) AS id FROM accounts").fetchone()["id"]
            if first_account is not None:
                _backfill_legacy_account_id(conn, first_account)
    finally:
        conn.close()


# --------------------------------------------------------- accounts & users
#
# An account is a tenant (one customer company); a user is a person who logs
# in and belongs to exactly one account. The FIRST signup creates account #1
# and becomes owner of the existing (pre-multi-tenant) data once Phase 3
# back-fills account_id — that's why nothing is auto-seeded here.


def email_exists(email: str) -> bool:
    conn = _connect()
    try:
        return conn.execute("SELECT 1 FROM users WHERE email = ?", (email.lower(),)).fetchone() is not None
    finally:
        conn.close()


def create_account_with_owner(company_name: str, user_name: str, email: str, password_hash: str) -> dict:
    """Creates the tenant + its first (owner) user in one transaction.
    Returns {'account_id', 'user_id'}. Caller must have checked email_exists.

    The very first account ever created (id == 1) adopts any pre-existing,
    pre-multi-tenant data instead of starting from zero — that's the "your
    current account becomes the first real customer" rule. Every account
    after that starts empty except for one default agent to test with.
    """
    conn = _connect()
    try:
        with conn:
            cur = conn.execute("INSERT INTO accounts (name) VALUES (?) RETURNING id", (company_name,))
            account_id = cur.lastrowid
            cur = conn.execute(
                "INSERT INTO users (account_id, email, name, password_hash, role) VALUES (?, ?, ?, ?, 'owner') "
                "RETURNING id",
                (account_id, email.lower(), user_name, password_hash),
            )
            user_id = cur.lastrowid
            if email.lower() == _PLATFORM_OWNER_EMAIL:
                conn.execute("UPDATE accounts SET is_platform_owner = 1 WHERE id = ?", (account_id,))
            if account_id == 1:
                _backfill_legacy_account_id(conn, account_id)
                # Legacy (pre-Postgres) installs already have settings/
                # integrations rows under account_id=1 from the old SQLite
                # migrations — only top up whichever keys a from-scratch
                # install wouldn't have yet.
                for key, value in (
                    ("credits_total", "300"),
                    ("credit_rate_browser", "1"),
                    ("credit_rate_phone", "1.5"),
                    ("credit_rate_widget", "1"),
                ):
                    conn.execute(
                        "INSERT INTO settings (account_id, key, value) VALUES (?, ?, ?) "
                        "ON CONFLICT (account_id, key) DO NOTHING",
                        (account_id, key, value),
                    )
                for skey, sname, scategory, sdescription in _SEED_INTEGRATIONS:
                    conn.execute(
                        "INSERT INTO integrations (account_id, key, name, category, description) "
                        "VALUES (?, ?, ?, ?, ?) ON CONFLICT (account_id, key) DO NOTHING",
                        (account_id, skey, sname, scategory, sdescription),
                    )
                if conn.execute(
                    "SELECT COUNT(*) c FROM agents WHERE account_id = ?", (account_id,)
                ).fetchone()["c"] == 0:
                    provision_account_defaults(conn, account_id)
            else:
                provision_account_defaults(conn, account_id)
            return {"account_id": account_id, "user_id": user_id}
    finally:
        conn.close()


def get_user_by_email(email: str) -> dict | None:
    """Includes password_hash — for the login path only."""
    conn = _connect()
    try:
        row = conn.execute("SELECT * FROM users WHERE email = ?", (email.lower(),)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_user_by_id(user_id: int) -> dict | None:
    """The safe shape for /auth/me — joins the account and omits the hash."""
    conn = _connect()
    try:
        row = conn.execute(
            """
            SELECT u.id, u.email, u.name, u.role, u.account_id,
                   a.name AS account_name, a.plan AS account_plan,
                   a.is_platform_owner
            FROM users u JOIN accounts a ON a.id = u.account_id
            WHERE u.id = ?
            """,
            (user_id,),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_password_hash(user_id: int) -> str | None:
    conn = _connect()
    try:
        row = conn.execute("SELECT password_hash FROM users WHERE id = ?", (user_id,)).fetchone()
        return row["password_hash"] if row else None
    finally:
        conn.close()


def update_user_profile(user_id: int, name: str | None = None, password_hash: str | None = None) -> None:
    conn = _connect()
    try:
        with conn:
            if name is not None:
                conn.execute("UPDATE users SET name = ? WHERE id = ?", (name, user_id))
            if password_hash is not None:
                conn.execute("UPDATE users SET password_hash = ? WHERE id = ?", (password_hash, user_id))
    finally:
        conn.close()


def update_account(account_id: int, name: str | None = None) -> None:
    conn = _connect()
    try:
        with conn:
            if name is not None:
                conn.execute("UPDATE accounts SET name = ? WHERE id = ?", (name, account_id))
    finally:
        conn.close()


# ---------------------------------------------------------------- calls


def _sentiment(transcript: list[dict]) -> str:
    visitor_text = " ".join(
        t.get("text", "").lower() for t in transcript if t.get("role") == "user"
    )
    negative = sum(1 for w in _NEGATIVE_WORDS if w in visitor_text)
    positive = sum(1 for w in _POSITIVE_WORDS if w in visitor_text)
    if negative > positive:
        return "negative"
    if positive > negative:
        return "positive"
    return "neutral"


def _status(row: dict, transcript: list[dict]) -> str:
    # A call that ended almost immediately with nothing captured and no real
    # exchange is a drop/failure; everything else completed.
    if (row["duration_seconds"] or 0) < 10 and not row["lead_name"] and len(transcript) < 2:
        return "failed"
    return "completed"


def _lead_status(row: dict) -> str:
    if row["site_visit_json"]:
        return "Site Visit Booked"
    if row["lead_name"]:
        return "Qualified"
    return "New"


def _initials(name: str) -> str:
    return ("".join(p[0] for p in name.split()[:2])).upper() or "?"


_CHANNEL_LABELS = {"phone": "Phone", "widget": "Website Widget", "browser": "Web"}


def _agent_names_by_id(account_id: int) -> dict[int, str]:
    conn = _connect()
    try:
        return {
            r["id"]: r["name"]
            for r in conn.execute("SELECT id, name FROM agents WHERE account_id = ?", (account_id,)).fetchall()
        }
    finally:
        conn.close()


def _call_dict(
    row: dict,
    include_transcript: bool = True,
    sites_by_id: dict[int, dict] | None = None,
    agent_names: dict[int, str] | None = None,
) -> dict:
    transcript = json.loads(row["transcript_json"]) if row["transcript_json"] else []
    name = row["lead_name"] or row["visitor_identity"] or "Unknown caller"
    call_type = row["call_type"] or "browser"
    site_id = row["site_id"]
    site = sites_by_id.get(site_id) if sites_by_id and site_id else None
    website = (site.get("allowedDomain") or site.get("name")) if site else ""
    # Rows from before the agent_id column (or with a since-deleted agent)
    # fall back to the first agent's name — historically the only one.
    agent_names = agent_names or {}
    agent_name = agent_names.get(row["agent_id"]) or next(iter(agent_names.values()), "Agent")
    out = {
        "id": str(row["id"]),
        "name": name,
        "initials": _initials(name),
        "phone": row["lead_phone"] or "",
        "budget": row["lead_budget"] or "",
        "location": row["lead_location"] or "",
        "timeline": row["lead_timeline"] or "",
        "company": row["lead_company"] or "",
        "useCase": row["lead_use_case"] or "",
        "teamSize": row["lead_team_size"] or "",
        "extractedData": _load_json_field(row["extracted_data"], {}),
        "status": _lead_status(row),
        "callStatus": _status(row, transcript),
        "sentiment": _sentiment(transcript),
        "channel": _CHANNEL_LABELS.get(call_type, "Web"),
        "callType": call_type,
        "siteId": site_id,
        "website": website,
        "agent": agent_name,
        "agentId": row["agent_id"],
        "callDate": row["started_at"],
        "durationSeconds": row["duration_seconds"],
        "replyLanguage": row["reply_language"],
        "siteVisit": json.loads(row["site_visit_json"]) if row["site_visit_json"] else None,
    }
    if include_transcript:
        out["transcript"] = [
            {
                "speaker": "agent" if t.get("role") == "assistant" else "visitor",
                "text": t.get("text", ""),
            }
            for t in transcript
        ]
    return out


def list_calls(account_id: int, limit: int = 200, search: str = "", status: str = "", days: int = 0) -> list[dict]:
    sites_by_id = {s["id"]: s for s in list_sites(account_id)}
    agent_names = _agent_names_by_id(account_id)
    conn = _connect()
    try:
        query = "SELECT * FROM calls WHERE account_id = ?"
        params: list = [account_id]
        if days:
            query += " AND started_at::date >= (CURRENT_DATE - (? || ' days')::interval)::date"
            params.append(str(days - 1))
        query += " ORDER BY started_at DESC LIMIT ?"
        params.append(limit)
        rows = conn.execute(query, params).fetchall()
        calls = [
            _call_dict(r, include_transcript=False, sites_by_id=sites_by_id, agent_names=agent_names)
            for r in rows
        ]
        if search:
            s = search.lower()
            calls = [c for c in calls if s in c["name"].lower() or s in c["phone"]]
        if status:
            calls = [c for c in calls if c["callStatus"] == status or c["status"] == status]
        return calls
    finally:
        conn.close()


def get_call(call_id: int, account_id: int) -> dict | None:
    conn = _connect()
    try:
        row = conn.execute("SELECT * FROM calls WHERE id = ? AND account_id = ?", (call_id, account_id)).fetchone()
        if not row:
            return None
        sites_by_id = {s["id"]: s for s in list_sites(account_id)}
        return _call_dict(row, sites_by_id=sites_by_id, agent_names=_agent_names_by_id(account_id))
    finally:
        conn.close()


def calls_csv(account_id: int) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        ["id", "caller", "phone", "status", "channel", "website", "duration_seconds", "sentiment", "agent", "language", "time"]
    )
    for c in list_calls(account_id, limit=10000):
        writer.writerow(
            [c["id"], c["name"], c["phone"], c["callStatus"], c["channel"], c["website"],
             c["durationSeconds"], c["sentiment"], c["agent"], c["replyLanguage"], c["callDate"]]
        )
    return buf.getvalue()


# ------------------------------------------------------------- dashboard


def summary(account_id: int) -> dict:
    conn = _connect()
    try:
        row = conn.execute(
            """
            SELECT COUNT(*) AS total,
                   SUM(CASE WHEN lead_name IS NOT NULL THEN 1 ELSE 0 END) AS qualified,
                   SUM(CASE WHEN site_visit_json IS NOT NULL THEN 1 ELSE 0 END) AS visits,
                   COALESCE(SUM(duration_seconds), 0) AS total_seconds,
                   COALESCE(AVG(duration_seconds), 0) AS avg_seconds
            FROM calls WHERE account_id = ?
            """,
            (account_id,),
        ).fetchone()
        agents_live = conn.execute(
            "SELECT COUNT(*) c FROM agents WHERE status = 'live' AND account_id = ?", (account_id,)
        ).fetchone()["c"]
        total = row["total"] or 0
        qualified = row["qualified"] or 0
        visits = row["visits"] or 0
        return {
            "totalCalls": total,
            "qualifiedCalls": qualified,
            "siteVisits": visits,
            "qualifiedRatio": (qualified / total) if total else 0.0,
            "conversionRatio": (visits / total) if total else 0.0,
            "totalMinutes": round((row["total_seconds"] or 0) / 60, 1),
            "avgDurationSeconds": row["avg_seconds"] or 0.0,
            "activeAgents": agents_live,
        }
    finally:
        conn.close()


def usage_trends(account_id: int, days: int = 14) -> dict:
    conn = _connect()
    try:
        rows = conn.execute(
            """
            SELECT started_at::date::text AS day,
                   COUNT(*) AS total,
                   SUM(CASE WHEN lead_name IS NOT NULL THEN 1 ELSE 0 END) AS qualified,
                   COALESCE(SUM(duration_seconds), 0) / 60.0 AS minutes
            FROM calls
            WHERE account_id = ? AND started_at::date >= (CURRENT_DATE - (? || ' days')::interval)::date
            GROUP BY day ORDER BY day
            """,
            (account_id, str(days - 1)),
        ).fetchall()
        return {
            "labels": [r["day"] for r in rows],
            "calls": [r["total"] for r in rows],
            "qualified": [r["qualified"] for r in rows],
            "minutes": [round(r["minutes"], 1) for r in rows],
        }
    finally:
        conn.close()


def analytics(account_id: int) -> dict:
    conn = _connect()
    try:
        languages = [
            {"language": r["reply_language"] or "unknown", "count": r["c"]}
            for r in conn.execute(
                "SELECT reply_language, COUNT(*) c FROM calls WHERE account_id = ? GROUP BY reply_language ORDER BY c DESC",
                (account_id,),
            ).fetchall()
        ]
        hours = [
            {"hour": int(r["h"]), "count": r["c"]}
            for r in conn.execute(
                "SELECT to_char(started_at::timestamp, 'HH24') h, COUNT(*) c FROM calls "
                "WHERE account_id = ? GROUP BY h ORDER BY h",
                (account_id,),
            ).fetchall()
        ]
        duration_trend = [
            {"day": r["day"], "avgSeconds": round(r["avg_s"] or 0, 1)}
            for r in conn.execute(
                """
                SELECT started_at::date::text AS day, AVG(duration_seconds) avg_s FROM calls
                WHERE account_id = ? AND started_at::date >= (CURRENT_DATE - INTERVAL '13 days')::date
                GROUP BY day ORDER BY day
                """,
                (account_id,),
            ).fetchall()
        ]
        rows = conn.execute("SELECT * FROM calls WHERE account_id = ?", (account_id,)).fetchall()
        sentiment = {"positive": 0, "neutral": 0, "negative": 0}
        engaged = 0
        for row in rows:
            transcript = json.loads(row["transcript_json"]) if row["transcript_json"] else []
            sentiment[_sentiment(transcript)] += 1
            if len(transcript) >= 4:
                engaged += 1
        # Calls + qualification split by channel (Web / Website Widget /
        # Phone) and by handling agent — the "which channel and which agent
        # actually convert" view the dashboard's analytics tab charts.
        by_channel = [
            {
                "channel": _CHANNEL_LABELS.get(r["t"], "Web"),
                "calls": r["c"],
                "qualified": r["q"] or 0,
                "minutes": round(r["s"] / 60, 1),
            }
            for r in conn.execute(
                """
                SELECT COALESCE(call_type, 'browser') t, COUNT(*) c,
                       SUM(CASE WHEN lead_name IS NOT NULL THEN 1 ELSE 0 END) q,
                       COALESCE(SUM(duration_seconds), 0) s
                FROM calls WHERE account_id = ? GROUP BY t ORDER BY c DESC
                """,
                (account_id,),
            ).fetchall()
        ]
        agent_names = _agent_names_by_id(account_id)
        fallback_agent = next(iter(agent_names.values()), "Agent")
        # Merge by display name, not agent_id: legacy rows (agent_id NULL,
        # from before the column existed) resolve to the first agent's name
        # and should count as that agent, not as a second phantom bar.
        by_agent_map: dict[str, dict] = {}
        for r in conn.execute(
            """
            SELECT agent_id, COUNT(*) c,
                   SUM(CASE WHEN lead_name IS NOT NULL THEN 1 ELSE 0 END) q,
                   COALESCE(SUM(duration_seconds), 0) s
            FROM calls WHERE account_id = ? GROUP BY agent_id
            """,
            (account_id,),
        ).fetchall():
            label = agent_names.get(r["agent_id"]) or fallback_agent
            entry = by_agent_map.setdefault(label, {"agent": label, "calls": 0, "qualified": 0, "seconds": 0.0})
            entry["calls"] += r["c"]
            entry["qualified"] += r["q"] or 0
            entry["seconds"] += r["s"]
        by_agent = [
            {"agent": e["agent"], "calls": e["calls"], "qualified": e["qualified"], "minutes": round(e["seconds"] / 60, 1)}
            for e in sorted(by_agent_map.values(), key=lambda e: -e["calls"])
        ]
        s = summary(account_id)
        return {
            "languages": languages,
            "peakHours": hours,
            "durationTrend": duration_trend,
            "sentiment": sentiment,
            "byChannel": by_channel,
            "byAgent": by_agent,
            "funnel": {
                "answered": s["totalCalls"],
                "engaged": engaged,
                "qualified": s["qualifiedCalls"],
                "visitBooked": s["siteVisits"],
            },
        }
    finally:
        conn.close()


# ---------------------------------------------------------------- agents

_AGENT_FIELDS = (
    "name", "description", "model", "voice", "language", "status",
    "system_prompt", "kb_id", "tone", "is_platform_demo",
    "first_speaker", "welcome_message", "interruption_sensitivity",
    "silence_reminder_ms", "silence_reminder_max", "end_call_on_silence_ms",
    "max_call_duration_s", "enabled_functions", "transfer_phone",
    "custom_functions", "post_call_fields", "webhook_url", "memory_enabled",
)
# INTEGER columns fed from a JSON bool (Postgres has no bool->int cast).
_AGENT_BOOL_FIELDS = frozenset({"is_platform_demo", "memory_enabled"})
# TEXT columns that hold a JSON array — the frontend sends a real
# array/object, stored as a JSON string, parsed back out in _agent_dict.
_AGENT_JSON_FIELDS = frozenset({"custom_functions", "post_call_fields"})
# camelCase (API) -> snake_case (column) for every field whose names differ.
_AGENT_CAMEL_TO_SNAKE = {
    "systemPrompt": "system_prompt",
    "kbId": "kb_id",
    "isPlatformDemo": "is_platform_demo",
    "firstSpeaker": "first_speaker",
    "welcomeMessage": "welcome_message",
    "interruptionSensitivity": "interruption_sensitivity",
    "silenceReminderMs": "silence_reminder_ms",
    "silenceReminderMax": "silence_reminder_max",
    "endCallOnSilenceMs": "end_call_on_silence_ms",
    "maxCallDurationS": "max_call_duration_s",
    "enabledFunctions": "enabled_functions",
    "transferPhone": "transfer_phone",
    "customFunctions": "custom_functions",
    "postCallFields": "post_call_fields",
    "webhookUrl": "webhook_url",
    "memoryEnabled": "memory_enabled",
}


def _load_json_field(raw: str | None, default):
    if not raw:
        return default
    try:
        return json.loads(raw)
    except (ValueError, TypeError):
        return default


def _agent_dict(row: dict) -> dict:
    return {
        "id": row["id"],
        "name": row["name"],
        "description": row["description"],
        "model": row["model"],
        "voice": row["voice"],
        "language": row["language"],
        "status": row["status"],
        "systemPrompt": row["system_prompt"],
        "kbId": row["kb_id"],
        "tone": row["tone"] or "balanced",
        "isPlatformDemo": bool(row["is_platform_demo"]),
        "firstSpeaker": row["first_speaker"] or "agent",
        "welcomeMessage": row["welcome_message"] or "",
        "interruptionSensitivity": row["interruption_sensitivity"] if row["interruption_sensitivity"] is not None else 0.5,
        "silenceReminderMs": row["silence_reminder_ms"] or 0,
        "silenceReminderMax": row["silence_reminder_max"] or 1,
        "endCallOnSilenceMs": row["end_call_on_silence_ms"] or 0,
        "maxCallDurationS": row["max_call_duration_s"] or 0,
        "enabledFunctions": row["enabled_functions"] or "",
        "transferPhone": row["transfer_phone"] or "",
        "customFunctions": _load_json_field(row["custom_functions"], []),
        "postCallFields": _load_json_field(row["post_call_fields"], []),
        "webhookUrl": row["webhook_url"] or "",
        "memoryEnabled": bool(row["memory_enabled"]),
        "createdAt": row["created_at"],
        "updatedAt": row["updated_at"],
    }


def agent_account_id(agent_id: int) -> int | None:
    """Which account owns this agent — used to attribute a live LiveKit room
    (tagged with just an agent_id) back to a tenant for /active-calls."""
    conn = _connect()
    try:
        row = conn.execute("SELECT account_id FROM agents WHERE id = ?", (agent_id,)).fetchone()
        return row["account_id"] if row else None
    finally:
        conn.close()


def is_platform_owner(account_id: int) -> bool:
    """Whether this account may flag one of its agents as
    agents.is_platform_demo — every other tenant must not be able to redirect
    the public marketing site's live demo to their own agent. Checked by the
    PATCH /agents/{id} route before honoring an isPlatformDemo change."""
    conn = _connect()
    try:
        row = conn.execute("SELECT is_platform_owner FROM accounts WHERE id = ?", (account_id,)).fetchone()
        return bool(row and row["is_platform_owner"])
    finally:
        conn.close()


def list_agents(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            _agent_dict(r)
            for r in conn.execute("SELECT * FROM agents WHERE account_id = ? ORDER BY id", (account_id,)).fetchall()
        ]
    finally:
        conn.close()


def create_agent(data: dict, account_id: int) -> dict:
    conn = _connect()
    try:
        with conn:
            cur = conn.execute(
                "INSERT INTO agents (account_id, name, description, model, voice, language, system_prompt) "
                "VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id",
                (
                    account_id,
                    data.get("name", "Unnamed agent"),
                    data.get("description", ""),
                    data.get("model", "gpt-4.1"),
                    data.get("voice", "shubh"),
                    data.get("language", "hi-IN"),
                    data.get("systemPrompt", ""),
                ),
            )
        row = conn.execute("SELECT * FROM agents WHERE id = ?", (cur.lastrowid,)).fetchone()
        return _agent_dict(row)
    finally:
        conn.close()


def update_agent(agent_id: int, data: dict, account_id: int) -> dict | None:
    conn = _connect()
    try:
        sets, params = [], []
        for key, value in data.items():
            column = _AGENT_CAMEL_TO_SNAKE.get(key, key)
            if column not in _AGENT_FIELDS:
                continue
            if column == "kb_id" and value is not None:
                # Refuse to point this agent at a knowledge base the caller's
                # account doesn't own — otherwise a crafted kbId would let one
                # tenant's agent read another tenant's KB content at call time.
                owned = conn.execute(
                    "SELECT 1 FROM knowledge_bases WHERE id = ? AND account_id = ?", (value, account_id)
                ).fetchone()
                if not owned:
                    continue
            if column in _AGENT_BOOL_FIELDS:
                # Postgres has no boolean->integer cast, and these columns are
                # INTEGER — a raw Python bool from the JSON body fails the
                # UPDATE outright rather than coercing. Same pattern as
                # set_kb_strict.
                value = 1 if value else 0
            elif column in _AGENT_JSON_FIELDS:
                # Frontend sends a real array/object; store it as a JSON string
                # (already-a-string values pass through untouched).
                if not isinstance(value, str):
                    value = json.dumps(value or [])
            sets.append(f"{column} = ?")
            params.append(value)
        if not sets:
            return None
        with conn:
            if data.get("is_platform_demo") or data.get("isPlatformDemo"):
                # At most one agent platform-wide answers the public marketing
                # demo — clear any previous holder before this one claims it.
                conn.execute("UPDATE agents SET is_platform_demo = 0 WHERE id != ?", (agent_id,))
            conn.execute(
                f"UPDATE agents SET {', '.join(sets)}, updated_at = {_NOW} WHERE id = ? AND account_id = ?",
                (*params, agent_id, account_id),
            )
        row = conn.execute("SELECT * FROM agents WHERE id = ? AND account_id = ?", (agent_id, account_id)).fetchone()
        return _agent_dict(row) if row else None
    finally:
        conn.close()


def delete_agent(agent_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM agents WHERE id = ? AND account_id = ?", (agent_id, account_id))
    finally:
        conn.close()


# -------------------------------------------------------------- api keys

_API_KEY_PREFIX = "vv_live_"


def _hash_api_key(key: str) -> str:
    return hashlib.sha256(key.encode()).hexdigest()


def create_api_key(account_id: int, name: str) -> dict:
    """Mint a new key for the account. The full key is returned ONCE here and
    never stored — only its SHA-256 and a display prefix persist."""
    secret = secrets.token_urlsafe(24)
    full_key = _API_KEY_PREFIX + secret
    prefix = full_key[: len(_API_KEY_PREFIX) + 6]  # e.g. vv_live_ab12cd
    conn = _connect()
    try:
        with conn:
            cur = conn.execute(
                "INSERT INTO api_keys (account_id, name, prefix, key_hash) VALUES (?, ?, ?, ?) RETURNING id",
                (account_id, name.strip() or "API key", prefix, _hash_api_key(full_key)),
            )
        row = conn.execute("SELECT * FROM api_keys WHERE id = ?", (cur.lastrowid,)).fetchone()
        return {
            "id": row["id"],
            "name": row["name"],
            "prefix": row["prefix"],
            "createdAt": row["created_at"],
            # The one and only time the caller sees the full key.
            "key": full_key,
        }
    finally:
        conn.close()


def list_api_keys(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            {
                "id": r["id"],
                "name": r["name"],
                "prefix": r["prefix"],
                "lastUsedAt": r["last_used_at"],
                "createdAt": r["created_at"],
            }
            for r in conn.execute(
                "SELECT * FROM api_keys WHERE account_id = ? ORDER BY id DESC", (account_id,)
            ).fetchall()
        ]
    finally:
        conn.close()


def delete_api_key(key_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM api_keys WHERE id = ? AND account_id = ?", (key_id, account_id))
    finally:
        conn.close()


def resolve_api_key(full_key: str) -> int | None:
    """Account id a raw API key belongs to (and bump last_used), or None if it
    isn't a valid key. Constant-time-ish: we look up by hash, not by scanning."""
    if not full_key or not full_key.startswith(_API_KEY_PREFIX):
        return None
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT id, account_id FROM api_keys WHERE key_hash = ?", (_hash_api_key(full_key),)
        ).fetchone()
        if row is None:
            return None
        with conn:
            conn.execute(f"UPDATE api_keys SET last_used_at = {_NOW} WHERE id = ?", (row["id"],))
        return row["account_id"]
    finally:
        conn.close()


def account_owner_user_id(account_id: int) -> int | None:
    """The owner user of an account — used to give an API-key-authed request a
    user identity for handlers that need one."""
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT id FROM users WHERE account_id = ? ORDER BY (role = 'owner') DESC, id LIMIT 1",
            (account_id,),
        ).fetchone()
        return row["id"] if row else None
    finally:
        conn.close()


# ------------------------------------------------------- password resets

_RESET_TTL_SECONDS = 60 * 60  # 1 hour


def create_password_reset(user_id: int) -> str:
    """Mint a single-use reset token for a user. Returns the raw token (goes in
    the emailed link); only its hash is stored."""
    token = secrets.token_urlsafe(32)
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO password_resets (user_id, token_hash, expires_at) VALUES (?, ?, ?)",
                (user_id, _hash_api_key(token), int(time.time()) + _RESET_TTL_SECONDS),
            )
        return token
    finally:
        conn.close()


def consume_password_reset(token: str) -> int | None:
    """Validate + burn a reset token, returning the user_id if it's valid,
    unexpired, and unused; otherwise None."""
    if not token:
        return None
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT id, user_id, expires_at, used FROM password_resets WHERE token_hash = ?",
            (_hash_api_key(token),),
        ).fetchone()
        if row is None or row["used"] or row["expires_at"] < int(time.time()):
            return None
        with conn:
            conn.execute("UPDATE password_resets SET used = 1 WHERE id = ?", (row["id"],))
        return row["user_id"]
    finally:
        conn.close()


# -------------------------------------------------------------- contacts


def _sync_contacts_from_calls(conn: dbconn.Conn, account_id: int) -> None:
    """Upsert a contact for every call that captured a phone number."""
    rows = conn.execute(
        """
        SELECT lead_phone,
               (ARRAY_AGG(lead_name ORDER BY started_at DESC))[1] lead_name,
               MAX(started_at) last_call,
               MAX(CASE WHEN site_visit_json IS NOT NULL THEN 1 ELSE 0 END) visited
        FROM calls WHERE account_id = ? AND lead_phone IS NOT NULL AND lead_phone != ''
        GROUP BY lead_phone
        """,
        (account_id,),
    ).fetchall()
    with conn:
        for row in rows:
            conn.execute(
                """
                INSERT INTO contacts (account_id, name, phone, status, source, last_called_at)
                VALUES (?, ?, ?, ?, 'call', ?)
                ON CONFLICT(account_id, phone) DO UPDATE SET
                    name = excluded.name,
                    status = excluded.status,
                    last_called_at = excluded.last_called_at
                """,
                (
                    account_id,
                    row["lead_name"] or "Unknown",
                    row["lead_phone"],
                    "site_visit" if row["visited"] else "qualified",
                    row["last_call"],
                ),
            )


def list_contacts(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        _sync_contacts_from_calls(conn, account_id)
        return [
            {
                "id": r["id"],
                "name": r["name"],
                "phone": r["phone"] or "",
                "email": r["email"],
                "status": r["status"],
                "tags": [t for t in (r["tags"] or "").split(",") if t],
                "source": r["source"],
                "lastCalledAt": r["last_called_at"],
                "createdAt": r["created_at"],
            }
            for r in conn.execute(
                "SELECT * FROM contacts WHERE account_id = ? ORDER BY created_at DESC", (account_id,)
            ).fetchall()
        ]
    finally:
        conn.close()


def create_contact(data: dict, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                """
                INSERT INTO contacts (account_id, name, phone, email, status, tags, source)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(account_id, phone) DO UPDATE SET
                    name = excluded.name, email = excluded.email,
                    status = excluded.status, tags = excluded.tags
                """,
                (
                    account_id,
                    data.get("name", "Unknown"),
                    data.get("phone") or None,
                    data.get("email", ""),
                    data.get("status", "new"),
                    ",".join(data.get("tags", [])) if isinstance(data.get("tags"), list) else data.get("tags", ""),
                    data.get("source", "manual"),
                ),
            )
    finally:
        conn.close()


def delete_contact(contact_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM contacts WHERE id = ? AND account_id = ?", (contact_id, account_id))
    finally:
        conn.close()


def delete_all_contacts(account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM contacts WHERE account_id = ?", (account_id,))
    finally:
        conn.close()


def contacts_csv(account_id: int) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["name", "phone", "email", "status", "tags", "source", "last_called_at"])
    for c in list_contacts(account_id):
        writer.writerow([c["name"], c["phone"], c["email"], c["status"], ";".join(c["tags"]), c["source"], c["lastCalledAt"]])
    return buf.getvalue()


def import_contacts_csv(text: str, account_id: int) -> int:
    reader = csv.DictReader(io.StringIO(text))
    count = 0
    for row in reader:
        normalized = {k.strip().lower(): (v or "").strip() for k, v in row.items() if k}
        if not normalized.get("name") and not normalized.get("phone"):
            continue
        create_contact(
            {
                "name": normalized.get("name") or "Unknown",
                "phone": normalized.get("phone"),
                "email": normalized.get("email", ""),
                "tags": normalized.get("tags", ""),
                "source": "import",
            },
            account_id,
        )
        count += 1
    return count


# ------------------------------------------------------- knowledge base


def list_knowledge_bases(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        kbs = []
        for kb in conn.execute(
            "SELECT * FROM knowledge_bases WHERE account_id = ? ORDER BY id", (account_id,)
        ).fetchall():
            sources = conn.execute(
                "SELECT id, name, type, length(content) size, created_at FROM knowledge_sources WHERE kb_id = ? ORDER BY id",
                (kb["id"],),
            ).fetchall()
            qa = conn.execute(
                "SELECT id, question, answer FROM kb_qa WHERE kb_id = ? ORDER BY position, id",
                (kb["id"],),
            ).fetchall()
            kbs.append(
                {
                    "id": kb["id"],
                    "name": kb["name"],
                    "strict": bool(kb["strict"]),
                    "createdAt": kb["created_at"],
                    "sources": [
                        {"id": s["id"], "name": s["name"], "type": s["type"], "sizeChars": s["size"], "createdAt": s["created_at"]}
                        for s in sources
                    ],
                    "qa": [{"id": q["id"], "question": q["question"], "answer": q["answer"]} for q in qa],
                }
            )
        return kbs
    finally:
        conn.close()


def create_knowledge_base(name: str, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("INSERT INTO knowledge_bases (account_id, name) VALUES (?, ?)", (account_id, name))
    finally:
        conn.close()


def delete_knowledge_base(kb_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM knowledge_sources WHERE kb_id = ?", (kb_id,))
            conn.execute("DELETE FROM kb_qa WHERE kb_id = ?", (kb_id,))
            conn.execute("DELETE FROM knowledge_bases WHERE id = ? AND account_id = ?", (kb_id, account_id))
            conn.execute("UPDATE agents SET kb_id = NULL WHERE kb_id = ? AND account_id = ?", (kb_id, account_id))
    finally:
        conn.close()


def set_kb_strict(kb_id: int, strict: bool, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE knowledge_bases SET strict = ? WHERE id = ? AND account_id = ?",
                (1 if strict else 0, kb_id, account_id),
            )
    finally:
        conn.close()


def kb_exists(kb_id: int, account_id: int) -> bool:
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT 1 FROM knowledge_bases WHERE id = ? AND account_id = ?", (kb_id, account_id)
        ).fetchone()
        return row is not None
    finally:
        conn.close()


def add_knowledge_source(kb_id: int, name: str, content: str, account_id: int, source_type: str = "text") -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO knowledge_sources (kb_id, name, type, content) "
                "SELECT ?, ?, ?, ? WHERE EXISTS (SELECT 1 FROM knowledge_bases WHERE id = ? AND account_id = ?)",
                (kb_id, name, source_type, content, kb_id, account_id),
            )
    finally:
        conn.close()


def update_knowledge_source(
    source_id: int, account_id: int, name: str | None = None, content: str | None = None
) -> dict | None:
    conn = _connect()
    try:
        sets, params = [], []
        if name is not None:
            sets.append("name = ?")
            params.append(name)
        if content is not None:
            sets.append("content = ?")
            params.append(content)
        if not sets:
            return get_knowledge_source_content(source_id, account_id)
        with conn:
            conn.execute(
                f"UPDATE knowledge_sources SET {', '.join(sets)} WHERE id = ? "
                "AND kb_id IN (SELECT id FROM knowledge_bases WHERE account_id = ?)",
                (*params, source_id, account_id),
            )
        return get_knowledge_source_content(source_id, account_id)
    finally:
        conn.close()


def delete_knowledge_source(source_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "DELETE FROM knowledge_sources WHERE id = ? "
                "AND kb_id IN (SELECT id FROM knowledge_bases WHERE account_id = ?)",
                (source_id, account_id),
            )
    finally:
        conn.close()


def get_knowledge_source_content(source_id: int, account_id: int) -> dict | None:
    """Full text of one source — the auto-extract endpoint feeds this to the
    LLM; the listing endpoint deliberately returns only length(content))."""
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT s.id, s.kb_id, s.name, s.content FROM knowledge_sources s "
            "JOIN knowledge_bases kb ON kb.id = s.kb_id "
            "WHERE s.id = ? AND kb.account_id = ?",
            (source_id, account_id),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


# Q&A pairs — the curated FAQ layer of a knowledge base (KB 2.0). Scoped via
# a same-account kb_id, same pattern as sources above.


def add_kb_qa(kb_id: int, question: str, answer: str, account_id: int) -> int | None:
    conn = _connect()
    try:
        with conn:
            if not conn.execute(
                "SELECT 1 FROM knowledge_bases WHERE id = ? AND account_id = ?", (kb_id, account_id)
            ).fetchone():
                return None
            pos = conn.execute(
                "SELECT COALESCE(MAX(position), 0) + 1 p FROM kb_qa WHERE kb_id = ?", (kb_id,)
            ).fetchone()["p"]
            cur = conn.execute(
                "INSERT INTO kb_qa (kb_id, question, answer, position) VALUES (?, ?, ?, ?) RETURNING id",
                (kb_id, question, answer, pos),
            )
            return cur.lastrowid
    finally:
        conn.close()


def add_kb_qa_bulk(kb_id: int, pairs: list[dict], account_id: int) -> int:
    """Insert several Q&A pairs at once (the accept step of auto-extract).
    Returns how many were added; blank questions/answers are skipped rather
    than stored as empty FAQ rows the agent would then recite."""
    conn = _connect()
    added = 0
    try:
        with conn:
            if not conn.execute(
                "SELECT 1 FROM knowledge_bases WHERE id = ? AND account_id = ?", (kb_id, account_id)
            ).fetchone():
                return 0
            pos = conn.execute(
                "SELECT COALESCE(MAX(position), 0) p FROM kb_qa WHERE kb_id = ?", (kb_id,)
            ).fetchone()["p"]
            for pair in pairs:
                question = (pair.get("question") or "").strip()
                answer = (pair.get("answer") or "").strip()
                if not question or not answer:
                    continue
                pos += 1
                conn.execute(
                    "INSERT INTO kb_qa (kb_id, question, answer, position) VALUES (?, ?, ?, ?)",
                    (kb_id, question, answer, pos),
                )
                added += 1
    finally:
        conn.close()
    return added


def update_kb_qa(qa_id: int, question: str, answer: str, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE kb_qa SET question = ?, answer = ? "
                "WHERE id = ? AND kb_id IN (SELECT id FROM knowledge_bases WHERE account_id = ?)",
                (question, answer, qa_id, account_id),
            )
    finally:
        conn.close()


def delete_kb_qa(qa_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "DELETE FROM kb_qa WHERE id = ? AND kb_id IN (SELECT id FROM knowledge_bases WHERE account_id = ?)",
                (qa_id, account_id),
            )
    finally:
        conn.close()


# ------------------------------------------------------------ campaigns


def list_inbound_routes(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM inbound_routes WHERE account_id = ? ORDER BY id DESC", (account_id,)
            ).fetchall()
        ]
    finally:
        conn.close()


def create_inbound_route(data: dict, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                """
                INSERT INTO inbound_routes
                    (account_id, phone_number, agent_id, timezone, max_concurrent, start_date, end_date,
                     window_start, window_end, active_days)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    account_id,
                    data.get("phoneNumber"),
                    data.get("agentId"),
                    data.get("timezone", "Asia/Kolkata"),
                    data.get("maxConcurrent", 1),
                    data.get("startDate"),
                    data.get("endDate"),
                    data.get("windowStart"),
                    data.get("windowEnd"),
                    ",".join(data.get("activeDays", [])) if isinstance(data.get("activeDays"), list) else data.get("activeDays", ""),
                ),
            )
    finally:
        conn.close()


def list_campaigns(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM campaigns WHERE account_id = ? ORDER BY id DESC", (account_id,)
            ).fetchall()
        ]
    finally:
        conn.close()


def create_campaign(data: dict, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                """
                INSERT INTO campaigns (account_id, name, agent_id, contact_tag, scheduled_date, window_start, window_end)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    account_id,
                    data.get("name", "Untitled campaign"),
                    data.get("agentId"),
                    data.get("contactTag", ""),
                    data.get("scheduledDate"),
                    data.get("windowStart"),
                    data.get("windowEnd"),
                ),
            )
    finally:
        conn.close()


def update_campaign_status(campaign_id: int, status: str, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE campaigns SET status = ? WHERE id = ? AND account_id = ?", (status, campaign_id, account_id)
            )
    finally:
        conn.close()


# ---------------------------------------------------------- integrations


def list_integrations(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            {
                "key": r["key"],
                "name": r["name"],
                "category": r["category"],
                "description": r["description"],
                "status": r["status"],
                "config": json.loads(r["config_json"] or "{}"),
                "lastSync": r["last_sync"],
            }
            for r in conn.execute("SELECT * FROM integrations WHERE account_id = ?", (account_id,)).fetchall()
        ]
    finally:
        conn.close()


def update_integration(key: str, status: str, config: dict, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE integrations SET status = ?, config_json = ? WHERE key = ? AND account_id = ?",
                (status, json.dumps(config), key, account_id),
            )
    finally:
        conn.close()


# -------------------------------------------------------- widget sites


def _new_site_key() -> str:
    import secrets

    # "av_live_" prefix makes a pasted key self-identifying in support
    # threads/screenshots, same idea as Stripe/OpenAI-style prefixed keys.
    return "av_live_" + secrets.token_urlsafe(24)


def _site_dict(r: dict) -> dict:
    return {
        "id": r["id"],
        "name": r["name"],
        "siteKey": r["site_key"],
        "allowedDomain": r["allowed_domain"],
        "agentId": r["agent_id"],
        "status": r["status"],
        "widgetPosition": r["widget_position"] or "bottom-right",
        "widgetLabel": r["widget_label"] or "Talk to us",
        "createdAt": r["created_at"],
    }


def list_sites(account_id: int) -> list[dict]:
    conn = _connect()
    try:
        return [
            _site_dict(r)
            for r in conn.execute("SELECT * FROM sites WHERE account_id = ? ORDER BY id DESC", (account_id,)).fetchall()
        ]
    finally:
        conn.close()


def get_site(site_id: int, account_id: int) -> dict | None:
    conn = _connect()
    try:
        row = conn.execute("SELECT * FROM sites WHERE id = ? AND account_id = ?", (site_id, account_id)).fetchone()
        return _site_dict(row) if row else None
    finally:
        conn.close()


def get_site_by_key(site_key: str) -> dict | None:
    """Unscoped by design — called from the public, unauthenticated
    /widget/token endpoint where the secret site_key IS the auth, embedded
    on a third-party website with no dashboard session available."""
    conn = _connect()
    try:
        row = conn.execute("SELECT * FROM sites WHERE site_key = ?", (site_key,)).fetchone()
        return _site_dict(row) if row else None
    finally:
        conn.close()


def create_site(
    name: str,
    agent_id: int | None,
    account_id: int,
    allowed_domain: str = "",
    widget_position: str = "bottom-right",
    widget_label: str = "Talk to us",
) -> dict:
    if widget_position not in ("bottom-right", "bottom-left"):
        widget_position = "bottom-right"
    conn = _connect()
    try:
        with conn:
            cur = conn.execute(
                "INSERT INTO sites (account_id, name, site_key, allowed_domain, agent_id, widget_position, widget_label) "
                "VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id",
                (account_id, name, _new_site_key(), allowed_domain, agent_id, widget_position, widget_label or "Talk to us"),
            )
        row = conn.execute("SELECT * FROM sites WHERE id = ?", (cur.lastrowid,)).fetchone()
        return _site_dict(row)
    finally:
        conn.close()


def update_site(site_id: int, data: dict, account_id: int) -> dict | None:
    widget_position = data.get("widgetPosition", "bottom-right")
    if widget_position not in ("bottom-right", "bottom-left"):
        widget_position = "bottom-right"
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE sites SET name = ?, allowed_domain = ?, agent_id = ?, status = ?, "
                "widget_position = ?, widget_label = ? WHERE id = ? AND account_id = ?",
                (
                    data.get("name"),
                    data.get("allowedDomain", ""),
                    data.get("agentId"),
                    data.get("status", "active"),
                    widget_position,
                    data.get("widgetLabel") or "Talk to us",
                    site_id,
                    account_id,
                ),
            )
        row = conn.execute("SELECT * FROM sites WHERE id = ? AND account_id = ?", (site_id, account_id)).fetchone()
        return _site_dict(row) if row else None
    finally:
        conn.close()


def delete_site(site_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM sites WHERE id = ? AND account_id = ?", (site_id, account_id))
    finally:
        conn.close()


def regenerate_site_key(site_id: int, account_id: int) -> dict | None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE sites SET site_key = ? WHERE id = ? AND account_id = ?", (_new_site_key(), site_id, account_id)
            )
        row = conn.execute("SELECT * FROM sites WHERE id = ? AND account_id = ?", (site_id, account_id)).fetchone()
        return _site_dict(row) if row else None
    finally:
        conn.close()


# --------------------------------------------------------------- billing


_CREDIT_RATE_SETTINGS = {
    "browser": "credit_rate_browser",
    "widget": "credit_rate_widget",
    "phone": "credit_rate_phone",
}


def credit_rates(account_id: int) -> dict:
    """Per-minute credit-burn multiplier for each call type, e.g.
    {"browser": 1.0, "widget": 1.0, "phone": 1.5} — phone calls burn more
    since they carry an EnableX telephony cost the others don't."""
    conn = _connect()
    try:
        rates = {}
        for call_type, setting_key in _CREDIT_RATE_SETTINGS.items():
            row = conn.execute(
                "SELECT value FROM settings WHERE account_id = ? AND key = ?", (account_id, setting_key)
            ).fetchone()
            rates[call_type] = float(row["value"]) if row else 1.0
        return rates
    finally:
        conn.close()


def set_credit_rate(call_type: str, rate: float, account_id: int) -> None:
    setting_key = _CREDIT_RATE_SETTINGS.get(call_type)
    if setting_key is None:
        raise ValueError(f"unknown call type: {call_type}")
    set_setting(setting_key, str(rate), account_id)


def billing_summary(account_id: int) -> dict:
    conn = _connect()
    try:
        total_row = conn.execute(
            "SELECT value FROM settings WHERE account_id = ? AND key = 'credits_total'", (account_id,)
        ).fetchone()
        credits_total = int(total_row["value"]) if total_row else 300
        rates = credit_rates(account_id)

        by_type: dict[str, float] = {}
        used = 0.0
        for row in conn.execute(
            "SELECT COALESCE(call_type, 'browser') call_type, "
            "COALESCE(SUM(duration_seconds), 0) / 60.0 m FROM calls WHERE account_id = ? GROUP BY call_type",
            (account_id,),
        ).fetchall():
            call_type = row["call_type"] if row["call_type"] in rates else "browser"
            minutes = row["m"]
            credits = minutes * rates.get(call_type, 1.0)
            by_type[call_type] = round(by_type.get(call_type, 0.0) + minutes, 1)
            used += credits
        used = round(used, 1)

        return {
            "creditsTotal": credits_total,
            "creditsUsed": used,
            "creditsRemaining": max(0, round(credits_total - used, 1)),
            "minutesUsed": round(sum(by_type.values()), 1),
            "minutesByType": by_type,
            "creditRates": rates,
        }
    finally:
        conn.close()


# --------------------------------------------------------- telephony (EnableX)

# Sentinel account_id for platform-level settings that are NOT tenant-specific
# — the shared LiveKit inbound SIP trunk id (livekit_sip.TRUNK_ID_SETTING) is
# one resource pooling every tenant's phone numbers, not per-account state.
# Real accounts start at id=1 (SQLite AUTOINCREMENT), so 0 never collides.
PLATFORM_ACCOUNT_ID = 0


def _get_setting(conn: dbconn.Conn, account_id: int, key: str) -> str | None:
    row = conn.execute(
        "SELECT value FROM settings WHERE account_id = ? AND key = ?", (account_id, key)
    ).fetchone()
    return row["value"] if row else None


def telephony_status(account_id: int) -> dict:
    """Connection state for the UI. Never returns the App Key — only whether
    one is set and a masked hint of the App ID."""
    conn = _connect()
    try:
        app_id = _get_setting(conn, account_id, "enablex_app_id")
        connected = bool(app_id and _get_setting(conn, account_id, "enablex_app_key"))
        masked = ""
        if app_id:
            masked = app_id[:4] + "…" + app_id[-4:] if len(app_id) > 8 else "set"
        return {"provider": "enablex", "connected": connected, "appIdHint": masked}
    finally:
        conn.close()


def connect_enablex(app_id: str, app_key: str, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            for key, value in (("enablex_app_id", app_id), ("enablex_app_key", app_key)):
                conn.execute(
                    "INSERT INTO settings (account_id, key, value) VALUES (?, ?, ?) "
                    "ON CONFLICT(account_id, key) DO UPDATE SET value = excluded.value",
                    (account_id, key, value),
                )
    finally:
        conn.close()


def disconnect_enablex(account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "DELETE FROM settings WHERE account_id = ? AND key IN ('enablex_app_id', 'enablex_app_key')",
                (account_id,),
            )
    finally:
        conn.close()


def _phone_number_dict(r: dict) -> dict:
    return {
        "id": r["id"],
        "accountId": r["account_id"],
        "number": r["number"],
        "label": r["label"],
        "provider": r["provider"],
        "agentId": r["agent_id"],
        "status": r["status"],
        "createdAt": r["created_at"],
        "lkTrunkId": r["lk_trunk_id"],
        "lkDispatchRuleId": r["lk_dispatch_rule_id"],
    }


def list_phone_numbers(account_id: int) -> list[dict]:
    """Dashboard-scoped listing — one tenant's own numbers page."""
    conn = _connect()
    try:
        return [
            _phone_number_dict(r)
            for r in conn.execute(
                "SELECT * FROM phone_numbers WHERE account_id = ? ORDER BY id DESC", (account_id,)
            ).fetchall()
        ]
    finally:
        conn.close()


def list_all_phone_numbers() -> list[dict]:
    """Unscoped — every tenant's numbers. Only for livekit_sip.py's shared SIP
    trunk management: one LiveKit inbound trunk pools ALL tenants' numbers and
    routes each to its own per-number dispatch rule, so building that trunk's
    numbers list is a platform-level concern, not a tenant-scoped read."""
    conn = _connect()
    try:
        return [_phone_number_dict(r) for r in conn.execute("SELECT * FROM phone_numbers ORDER BY id DESC").fetchall()]
    finally:
        conn.close()


def get_phone_number(number_id: int, account_id: int) -> dict | None:
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT * FROM phone_numbers WHERE id = ? AND account_id = ?", (number_id, account_id)
        ).fetchone()
        return _phone_number_dict(row) if row else None
    finally:
        conn.close()


def get_phone_number_by_number(number: str) -> dict | None:
    """Unscoped by design — called from the public EnableX inbound webhook,
    which has no dashboard session. The dialed number itself identifies which
    tenant (via the returned row's account_id) and which agent to route to."""
    conn = _connect()
    try:
        row = conn.execute("SELECT * FROM phone_numbers WHERE number = ?", (number,)).fetchone()
        return _phone_number_dict(row) if row else None
    finally:
        conn.close()


def add_phone_number(number: str, account_id: int, label: str = "", agent_id: int | None = None) -> int:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO phone_numbers (number, account_id, label, provider, agent_id) "
                "VALUES (?, ?, ?, 'enablex', ?) "
                "ON CONFLICT(number) DO UPDATE SET label = excluded.label, agent_id = excluded.agent_id",
                (number, account_id, label, agent_id),
            )
        return conn.execute("SELECT id FROM phone_numbers WHERE number = ?", (number,)).fetchone()["id"]
    finally:
        conn.close()


def assign_phone_number(number_id: int, agent_id: int | None, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE phone_numbers SET agent_id = ? WHERE id = ? AND account_id = ?",
                (agent_id, number_id, account_id),
            )
    finally:
        conn.close()


def set_phone_number_lk_ids(number_id: int, trunk_id: str | None, dispatch_rule_id: str | None) -> None:
    """Internal bookkeeping called right after the LiveKit trunk/dispatch rule
    for this number is created — the caller already resolved and validated
    number_id (e.g. via a scoped get_phone_number), so this step itself
    doesn't need an account_id filter."""
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "UPDATE phone_numbers SET lk_trunk_id = ?, lk_dispatch_rule_id = ? WHERE id = ?",
                (trunk_id, dispatch_rule_id, number_id),
            )
    finally:
        conn.close()


def delete_phone_number(number_id: int, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute("DELETE FROM phone_numbers WHERE id = ? AND account_id = ?", (number_id, account_id))
    finally:
        conn.close()


def get_setting(key: str, account_id: int) -> str | None:
    conn = _connect()
    try:
        return _get_setting(conn, account_id, key)
    finally:
        conn.close()


def set_setting(key: str, value: str, account_id: int) -> None:
    conn = _connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO settings (account_id, key, value) VALUES (?, ?, ?) "
                "ON CONFLICT(account_id, key) DO UPDATE SET value = excluded.value",
                (account_id, key, value),
            )
    finally:
        conn.close()


def enablex_credentials(account_id: int) -> tuple[str | None, str | None]:
    conn = _connect()
    try:
        return _get_setting(conn, account_id, "enablex_app_id"), _get_setting(conn, account_id, "enablex_app_key")
    finally:
        conn.close()


def _enablex_request(path: str, method: str, body: dict | None, account_id: int) -> dict:
    """Call the EnableX Voice REST API with the stored HTTP Basic credentials.

    `path` is relative to ENABLEX_API_BASE (e.g. "/call", "/call/<id>/accept").
    Returns {"ok": bool, ...} — never raises, so callers on the live-call path
    can degrade gracefully. Uses urllib to avoid adding a dependency.
    """
    import base64
    import json as _json
    import urllib.error
    import urllib.request

    app_id, app_key = enablex_credentials(account_id)
    if not app_id or not app_key:
        return {"ok": False, "error": "EnableX is not connected. Add your App ID and App Key first."}

    auth = base64.b64encode(f"{app_id}:{app_key}".encode()).decode()
    data = _json.dumps(body).encode() if body is not None else None
    request = urllib.request.Request(
        f"{ENABLEX_API_BASE}{path}",
        data=data,
        method=method,
        headers={"Authorization": f"Basic {auth}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=15) as resp:
            payload = _json.loads(resp.read().decode() or "{}")
            return {"ok": True, "response": payload}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:400]
        return {"ok": False, "error": f"EnableX returned {exc.code}: {detail}"}
    except Exception as exc:  # network/DNS/timeout
        return {"ok": False, "error": f"Could not reach EnableX: {exc}"}


def public_base_url() -> str | None:
    """Publicly reachable base URL of this backend, used for EnableX webhook
    URLs. Railway sets RAILWAY_PUBLIC_DOMAIN automatically on a service with
    a generated domain; PUBLIC_BASE_URL is an escape hatch for anything else
    (a custom domain, local ngrok testing, etc.)."""
    override = os.environ.get("PUBLIC_BASE_URL")
    if override:
        return override.rstrip("/")
    domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
    return f"https://{domain}" if domain else None


# voice_id -> (from_number, account_id) for outbound test calls awaiting
# their "connected" webhook, so we know both which agent's SIP number to
# bridge to and whose EnableX credentials to bridge with. EnableX's generic
# webhook from/to fields aren't reliably documented for the outbound
# direction, so we track this ourselves rather than trust them.
_TEST_CALL_FROM_BY_VOICE_ID: dict[str, tuple[str, int]] = {}


def place_test_call(from_number: str, to_number: str, account_id: int) -> dict:
    """Place a real outbound call through the EnableX Voice API. Once the
    destination answers (the "connected" webhook event), the outbound-test
    webhook bridges the leg to the LiveKit agent assigned to `from_number` —
    EnableX's action_on_connect only documents a "play" mode, not a bridge/
    connect mode, so the actual bridge has to go through their runtime
    connectVoice API (enablex_connect_to_sip), same as real inbound calls.
    This is what lets an operator actually talk to the agent (and hear it use
    the knowledge base) before running a campaign, instead of a canned line.
    """
    base_url = public_base_url()
    if not base_url:
        return {
            "ok": False,
            "error": "Set PUBLIC_BASE_URL (or deploy with a Railway public domain) so EnableX can "
            "notify this server when the test call connects.",
        }

    result = _enablex_request(
        "/call",
        "POST",
        {
            "name": "Vistrow Voice test call",
            "owner_ref": "vistrow-dashboard-test",
            "from": from_number,
            "to": to_number,
            "action_on_connect": {
                "play": {
                    "text": "Connecting you now.",
                    "voice": "female",
                    "language": "en-US",
                }
            },
            "event_url": f"{base_url}/telephony/enablex/outbound-test-event",
        },
        account_id,
    )
    voice_id = (result.get("response") or {}).get("voice_id") if result.get("ok") else None
    if voice_id:
        _TEST_CALL_FROM_BY_VOICE_ID[voice_id] = (from_number, account_id)
    return result


def enablex_test_call_connected(voice_id: str) -> dict | None:
    """Called from the outbound-test webhook once EnableX reports the callee
    answered ("connected"). Bridges the leg to the LiveKit SIP host for the
    agent assigned to whichever number placed this test call. Returns None
    if this voice_id isn't a tracked test call (e.g. a duplicate webhook
    delivery after we've already bridged it once)."""
    import livekit_sip  # local import: livekit_sip imports this module at load time

    tracked = _TEST_CALL_FROM_BY_VOICE_ID.pop(voice_id, None)
    if not tracked:
        return None
    from_number, account_id = tracked
    sip_uri = f"sip:{from_number}@{livekit_sip.sip_host()}"
    return enablex_connect_to_sip(voice_id, from_number, sip_uri, account_id)


def enablex_accept_call(voice_id: str, account_id: int) -> dict:
    """Answer a ringing inbound EnableX call leg (PUT /call/<id>/accept)."""
    return _enablex_request(f"/call/{voice_id}/accept", "PUT", None, account_id)


def enablex_connect_to_sip(voice_id: str, from_number: str, sip_uri: str, account_id: int) -> dict:
    """Bridge an accepted EnableX call leg out to a SIP URI (PUT /call/<id>/connect).

    EnableX's `connect` action accepts a phone number or a SIP URI as `to`,
    so pointing it at LiveKit's per-project SIP host hands the audio to the
    LiveKit agent while EnableX bridges the two legs.
    """
    return _enablex_request(
        f"/call/{voice_id}/connect",
        "PUT",
        {"from": from_number, "to": sip_uri},
        account_id,
    )
