"""Write the help articles for the public website build.

The website (web-demo, built on Vercel) can't import Python, so the public
/help pages read a generated TypeScript copy of help_articles.TOPICS. Run this after editing
help_articles.py:

    server/.venv/bin/python server/export_help_articles.py

test_help_articles.py fails if the committed JSON is out of date, so the
website and the in-app help centre can never drift apart.
"""

import json
from pathlib import Path

import help_articles

OUT = Path(__file__).resolve().parent.parent / "web-demo" / "src" / "content" / "helpArticles.ts"


def render() -> str:
    # A .ts module (not .json) so the website imports it typed, with no
    # tsconfig change. GENERATED — edit server/help_articles.py instead.
    return (
        "// GENERATED by server/export_help_articles.py from server/help_articles.py.\n"
        "// Do not edit by hand: change the Python source and re-run the exporter.\n"
        "import type { HelpTopic } from '../lib/types'\n\n"
        "export const HELP_TOPICS: HelpTopic[] = "
        + json.dumps(help_articles.TOPICS, ensure_ascii=False, indent=1)
        + "\n"
    )


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT} ({sum(len(t['articles']) for t in help_articles.TOPICS)} articles)")
