"""One-time data migration: copy the existing production SQLite database
(agent/calls.db) into the Postgres database at DATABASE_URL.

Run this once, right before cutting the running services over to Postgres
(server/calls_db.py and agent/db.py already require DATABASE_URL and will
refuse to start without it). Safe to re-run — every insert uses
ON CONFLICT DO NOTHING, so a repeat run just skips rows already copied.

Usage:
    DATABASE_URL=postgresql://... python scripts/migrate_sqlite_to_postgres.py [path/to/calls.db]

(or rely on .env / a --env-file if DATABASE_URL is already set there)
"""

import sqlite3
import sys
from pathlib import Path

import psycopg
from dotenv import load_dotenv

load_dotenv()

# Parent-before-child so foreign keys (account_id, agent_id, kb_id, site_id)
# always resolve to a row that's already been copied.
TABLE_ORDER = [
    "accounts",
    "users",
    "agents",
    "sites",
    "knowledge_bases",
    "knowledge_sources",
    "kb_qa",
    "calls",
    "contacts",
    "inbound_routes",
    "campaigns",
    "integrations",
    "phone_numbers",
    "settings",
]

# Tables with a plain single-column `id` primary key (GENERATED BY DEFAULT AS
# IDENTITY on the Postgres side) — need their sequence bumped past the
# highest copied id so future inserts don't collide with migrated rows.
# integrations/settings use a composite (account_id, key) key instead.
SEQUENCE_TABLES = {
    "accounts", "users", "agents", "sites", "knowledge_bases",
    "knowledge_sources", "kb_qa", "calls", "contacts", "inbound_routes",
    "campaigns", "phone_numbers",
}


def migrate(sqlite_path: str) -> None:
    sconn = sqlite3.connect(sqlite_path)
    sconn.row_factory = sqlite3.Row

    pconn = psycopg.connect(_database_url())

    try:
        with pconn.cursor() as pcur:
            for table in TABLE_ORDER:
                try:
                    rows = sconn.execute(f"SELECT * FROM {table}").fetchall()
                except sqlite3.OperationalError:
                    print(f"{table}: not present in source db (skipped)")
                    continue
                if not rows:
                    print(f"{table}: 0 rows (skipped)")
                    continue

                columns = rows[0].keys()
                col_list = ", ".join(columns)
                placeholders = ", ".join(["%s"] * len(columns))
                sql = (
                    f"INSERT INTO {table} ({col_list}) VALUES ({placeholders}) "
                    "ON CONFLICT DO NOTHING"
                )
                for row in rows:
                    pcur.execute(sql, tuple(row[c] for c in columns))

                if table in SEQUENCE_TABLES:
                    pcur.execute(
                        f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                        f"COALESCE((SELECT MAX(id) FROM {table}), 1), "
                        f"(SELECT MAX(id) FROM {table}) IS NOT NULL)"
                    )

                print(f"{table}: {len(rows)} rows copied")

        pconn.commit()
    finally:
        pconn.close()
        sconn.close()

    print("\nMigration complete.")


def _database_url() -> str:
    import os

    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set")
    return url


if __name__ == "__main__":
    default_path = Path(__file__).resolve().parent.parent / "agent" / "calls.db"
    sqlite_path = sys.argv[1] if len(sys.argv) > 1 else str(default_path)
    print(f"Migrating {sqlite_path} -> {{DATABASE_URL}}\n")
    migrate(sqlite_path)
