"""Local call-log storage.

Shares one Postgres database with server/calls_db.py (server owns agents,
knowledge_bases, kb_qa, integrations, etc.; this module owns `calls` and
writes completed-call rows, plus reads the tables it needs at call time).
Was SQLite through early development; moved to Postgres for the
durability/concurrency a sellable multi-tenant product needs — see
vistrow-voice-infrastructure-requirements.txt. dbconn.py (duplicated from
server/, since this package pulls in livekit-agents which isn't installed
in server's venv) is a thin shim that keeps every call site below in its
original sqlite3-flavored form (`?` placeholders, `with conn:` committing
without closing).
"""

import datetime
import json
import logging
import threading
import time

import psycopg
from zoneinfo import ZoneInfo

import dbconn

logger = logging.getLogger(__name__)

_SCHEMA = """
CREATE TABLE IF NOT EXISTS calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name TEXT NOT NULL,
    visitor_identity TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    duration_seconds REAL,
    reply_language TEXT,
    lead_name TEXT,
    lead_phone TEXT,
    lead_email TEXT,
    lead_budget TEXT,
    lead_location TEXT,
    lead_timeline TEXT,
    lead_company TEXT,
    lead_use_case TEXT,
    lead_team_size TEXT,
    site_visit_json TEXT,
    transcript_json TEXT NOT NULL,
    call_type TEXT DEFAULT 'browser',
    site_id INTEGER,
    agent_id INTEGER,
    account_id INTEGER,
    extracted_data TEXT DEFAULT '',
    latency_metrics_json TEXT DEFAULT ''
);

-- Mirrors server/calls_db.py — created here too so the agent works even if it
-- boots against a fresh DB before the backend has. Holds one rolling summary
-- per (agent, caller phone) for agents with memory enabled.
CREATE TABLE IF NOT EXISTS caller_memory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    agent_id INTEGER,
    caller_phone TEXT NOT NULL,
    summary TEXT DEFAULT '',
    updated_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text,
    UNIQUE(agent_id, caller_phone)
);
"""


def init_db() -> None:
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(_SCHEMA)
            # Whichever of server/agent boots first creates the base table via
            # CREATE TABLE IF NOT EXISTS above (a no-op if it already exists) —
            # columns added after go-live still need an explicit migration to
            # land, regardless of boot order.
            for column in (
                "lead_company", "lead_use_case", "lead_team_size", "lead_email",
                # Per-call ArthaLeads delivery outcome — see server/calls_db.py's
                # matching migration for why this is separate from the
                # integration-level last_sync/last_error.
                "arthaleads_status", "arthaleads_synced_at", "arthaleads_error",
                # Backblaze B2 object key for this call's recording (see
                # recording.py), set after the fact once upload finishes —
                # never the raw key surfaced to the frontend, only through a
                # presigned URL route.
                "recording_key",
            ):
                conn.execute(f"ALTER TABLE calls ADD COLUMN IF NOT EXISTS {column} TEXT")
            conn.execute("ALTER TABLE calls ADD COLUMN IF NOT EXISTS extracted_data TEXT DEFAULT ''")
            conn.execute("ALTER TABLE calls ADD COLUMN IF NOT EXISTS latency_metrics_json TEXT DEFAULT ''")
    finally:
        conn.close()


def get_caller_memory(agent_id: int, caller_phone: str) -> str:
    """The rolling summary of prior calls with this caller for this agent,
    or '' if none / memory table absent. Only phone calls have a stable
    caller_phone, so web calls never hit this."""
    if not caller_phone:
        return ""
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT summary FROM caller_memory WHERE agent_id = ? AND caller_phone = ?",
            (agent_id, caller_phone),
        ).fetchone()
        return (row["summary"] or "") if row else ""
    except psycopg.Error:
        return ""
    finally:
        conn.close()


def save_caller_memory(account_id: int | None, agent_id: int, caller_phone: str, summary: str) -> None:
    """Upsert the rolling summary for (agent, caller). Best-effort — a failure
    here must never break call teardown."""
    if not (caller_phone and summary):
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO caller_memory (account_id, agent_id, caller_phone, summary) "
                "VALUES (?, ?, ?, ?) "
                "ON CONFLICT (agent_id, caller_phone) DO UPDATE SET "
                "summary = EXCLUDED.summary, updated_at = (now() AT TIME ZONE 'utc')::text",
                (account_id, agent_id, caller_phone, summary),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist caller memory")
    finally:
        conn.close()


# agent_id (or None, for the unrouted "whichever is_platform_demo" lookup) ->
# (cached_at, config). Confirmed live 2026-08-19: LiveKit Cloud agent workers
# run in India West; Postgres runs in US West (moved there the same day to
# sit next to the orchestrator service) — a genuine trans-Pacific round trip
# for what should be a fast lookup, measured as a real 2-4s dead-air gap
# between a caller joining and session.start() actually beginning. A process
# handles many calls over its lifetime (num_idle_processes keeps it warm
# between jobs, not one-shot), and the platform-demo worker in particular
# fetches the exact same agent_id on nearly every single call, so an
# in-memory cache here has a real, meaningful hit rate — not just a
# theoretical one.
#
# TTL was originally 30s ("short, so a dashboard change reaches the next
# call within well under a minute") but real call data showed this backfired:
# calls on a low/medium-traffic agent are naturally spaced minutes apart, so
# a 30s TTL meant the cache was cold on nearly every call anyway — confirmed
# live on 2026-08-20 (get_kb_content, the equivalent cache below, still took
# 1.47s on a real widget call despite this fix already being deployed).
# Dashboard config edits are a rare, operator-driven event, not something
# that needs near-real-time propagation — 10 minutes gives the cache a real
# chance to actually warm up across realistic call spacing, while still
# keeping edits from going stale for a process's entire lifetime.
_agent_config_cache: dict[int | None, tuple[float, dict | None]] = {}
_AGENT_CONFIG_CACHE_TTL_S = 600.0


def get_agent_config(agent_id: int | None = None) -> dict | None:
    """Dashboard-managed agent settings (server/calls_db.py owns the table).

    With `agent_id`, loads that specific agent — used by inbound phone calls,
    where the LiveKit dispatch rule for the dialed number names which agent
    handles it. Without it (an unrouted browser call, notably the public
    marketing site's /demo and /call), prefers whichever agent is flagged
    is_platform_demo — see server/calls_db.py update_agent — falling back to
    the first agent by id if none is flagged yet. Returns None when the
    table doesn't exist yet (dashboard API never ran) or the id isn't found,
    so callers fall back to the in-code defaults and the agent keeps working
    standalone.
    """
    cached = _agent_config_cache.get(agent_id)
    now = time.monotonic()
    if cached is not None and now - cached[0] < _AGENT_CONFIG_CACHE_TTL_S:
        return cached[1]
    conn = dbconn.connect()
    try:
        # account_name joins in the tenant's own company name (accounts.name)
        # so the generic persona can say it aloud. LEFT JOIN, never INNER:
        # an agent whose account row is somehow missing must still take the
        # call (falling back to "this business") rather than disappear.
        if agent_id is not None:
            row = conn.execute(
                "SELECT a.*, acc.name AS account_name FROM agents a "
                "LEFT JOIN accounts acc ON acc.id = a.account_id WHERE a.id = ?",
                (agent_id,),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT a.*, acc.name AS account_name FROM agents a "
                "LEFT JOIN accounts acc ON acc.id = a.account_id "
                "ORDER BY a.is_platform_demo DESC, a.id LIMIT 1"
            ).fetchone()
        result = dict(row) if row else None
    except psycopg.Error:
        # A genuine query failure (DB unreachable, etc.) is never cached —
        # caching it would mean a 30s-stale None even after the DB recovers
        # on what would otherwise have been the very next successful call.
        return None
    finally:
        conn.close()
    _agent_config_cache[agent_id] = (now, result)
    return result


# Same reasoning as _AGENT_CONFIG_CACHE_TTL_S above — a 30s TTL was too
# short to ever actually warm up against realistic call spacing.
_kb_cache: dict[int, tuple[float, tuple[str, bool]]] = {}
_KB_CACHE_TTL_S = 600.0


def get_kb_content(kb_id: int, max_chars: int = 8000) -> str:
    """Knowledge-base text to append to the system prompt.

    Curated Q&A pairs (kb_qa, the operator-reviewed FAQ) come first so they
    always survive the char cap — they're the facts the operator explicitly
    signed off on — followed by raw sources with whatever budget remains.

    Prompt-stuffing rather than embeddings — right-sized while KBs are a few
    brochures/price sheets; swap for retrieval once sources outgrow this cap.
    """
    return get_kb(kb_id, max_chars)[0]


def is_kb_strict(kb_id: int) -> bool:
    """Whether the operator turned strict mode on for this KB (default yes)."""
    return get_kb(kb_id)[1]


def get_kb(kb_id: int, max_chars: int = 8000) -> tuple[str, bool]:
    """Combined (content, strict) fetch — one connection instead of the two
    get_kb_content/is_kb_strict used to open separately, and cached with the
    same 30s-TTL pattern as get_agent_config. Confirmed live (2026-08-19,
    call room=widget-5-b89683a199375e71) that the uncached two-connection
    version cost 1.16s on its own, entirely inside RealEstateAgent.__init__
    on the call's critical path — this was the single largest piece of the
    "still listening" gap reported after the caller stops talking, and
    predates streaming/turn-detection entirely: the agent hadn't even
    started session.start() yet."""
    cached = _kb_cache.get(kb_id)
    now = time.monotonic()
    if cached is not None and now - cached[0] < _KB_CACHE_TTL_S:
        return cached[1]
    conn = dbconn.connect()
    try:
        parts: list[str] = []
        try:
            qa_rows = conn.execute(
                "SELECT question, answer FROM kb_qa WHERE kb_id = ? ORDER BY position, id",
                (kb_id,),
            ).fetchall()
        except psycopg.Error:
            # kb_qa table doesn't exist yet (dashboard API predates KB 2.0).
            qa_rows = []
        if qa_rows:
            faq = "\n\n".join(f"Q: {r['question']}\nA: {r['answer']}" for r in qa_rows)
            parts.append("## Approved answers (quote these when the question matches)\n" + faq)
        rows = conn.execute(
            "SELECT name, content FROM knowledge_sources WHERE kb_id = ? ORDER BY id",
            (kb_id,),
        ).fetchall()
        parts.extend(f"## {r['name']}\n{r['content']}" for r in rows)
        content = "\n\n".join(parts)[:max_chars]
        strict_row = conn.execute("SELECT strict FROM knowledge_bases WHERE id = ?", (kb_id,)).fetchone()
        strict = bool(strict_row["strict"]) if strict_row is not None else True
    except psycopg.Error:
        # A genuine query failure is never cached — see get_agent_config's
        # identical reasoning.
        return "", True
    finally:
        conn.close()
    result = (content, strict)
    _kb_cache[kb_id] = (now, result)
    return result


def start_cache_prewarm() -> None:
    """Kick off the cache warm in a background thread and return immediately.

    MUST NOT BLOCK. LiveKit gives each job subprocess a bounded initialization
    window and kills the process when prewarm overruns it. Calling the
    blocking warm below directly cost ~14 database round-trips inside that
    window, which timed out every process ("error initializing process" ->
    TimeoutError -> exit code -10), left the worker with zero usable
    processes, and took inbound calls down entirely on 2026-08-21 until the
    deploy was rolled back. Starting a thread returns in microseconds, so the
    process is registered as ready straight away and the cache fills a moment
    later while nothing is waiting on it.

    A call arriving before the warm finishes is not a problem: get_agent_config
    and get_kb simply miss and do their own lookup, exactly as before. The
    caches are plain dicts written under the GIL, so the racing write is safe.
    """
    threading.Thread(target=prewarm_caches, name="cache-prewarm", daemon=True).start()


def prewarm_caches() -> None:
    """Fill this process's agent-config and KB caches before a call arrives.

    Blocking. Call start_cache_prewarm() from a worker; this stays public so
    the warm can be exercised directly in a test.

    Both caches live in module globals, so they are per-process. LiveKit hands
    each job an idle subprocess whose globals start empty, which meant every
    inbound call paid both lookups while the caller sat listening to ringing:
    measured on a real call 2026-08-21, 2.86s for the agent config plus 1.51s
    for the knowledge base, and LiveKit holds the SIP leg at 180 Ringing until
    the agent is ready. Raising the cache TTLs did nothing for this — a TTL
    only helps a process that has already done the lookup once.

    Called from main.py's _prewarm, i.e. in an idle process with nobody
    waiting. Best-effort by design: any failure here just leaves the caches
    cold and the first call pays what it always used to, which is never worth
    failing worker startup over.

    Only 'live' agents are warmed — paused ones cannot take a call, so their
    rows and (often large) knowledge bases are not worth the memory.
    """
    conn = dbconn.connect()
    try:
        rows = conn.execute(
            "SELECT a.*, acc.name AS account_name FROM agents a "
            "LEFT JOIN accounts acc ON acc.id = a.account_id WHERE a.status = 'live'"
        ).fetchall()
    except psycopg.Error:
        return
    finally:
        conn.close()

    now = time.monotonic()
    configs = [dict(r) for r in rows]
    for cfg in configs:
        _agent_config_cache[cfg["id"]] = (now, cfg)
    # get_agent_config(None) — an unrouted browser call — resolves to the
    # platform-demo agent, else the lowest id. Mirror that ordering here so
    # the default lookup is warm too.
    if configs:
        default = sorted(configs, key=lambda c: (not c.get("is_platform_demo"), c["id"]))[0]
        _agent_config_cache[None] = (now, default)

    for kb_id in {c["kb_id"] for c in configs if c.get("kb_id")}:
        try:
            get_kb(kb_id)  # reuse the real loader so the cached shape matches
        except Exception:
            pass

    for account_id in {c.get("account_id") for c in configs}:
        try:
            get_compliance_config(account_id)
        except Exception:
            pass

    # Registered inbound numbers. agent/main.py resolves the owning tenant
    # from the dialled number on every inbound call, before the greeting, so
    # leaving this uncached would put a fresh-connection query back on the
    # critical path and undo the saving above.
    conn = dbconn.connect()
    try:
        rows = conn.execute("SELECT number, account_id, agent_id FROM phone_numbers").fetchall()
    except psycopg.Error:
        return
    finally:
        conn.close()
    now = time.monotonic()
    for row in rows:
        d = dict(row)
        number = d.pop("number")
        _phone_number_cache[_normalize_sip_number(number)] = (now, d)


# Per-tenant compliance config (server/calls_db.py owns the settings row under
# "compliance.config"). Cached and prewarmed like the others because it is read
# on the call path: an uncached read here would put a fresh connection round
# trip in front of the caller, which is what the prewarm work removed.
_compliance_cache: dict[int | None, tuple[float, dict]] = {}
_COMPLIANCE_CACHE_TTL_S = 600.0

# Mirrors _COMPLIANCE_DEFAULTS in server/calls_db.py. Kept conservative: if the
# row is missing or unreadable we must NOT invent permission to record.
_COMPLIANCE_FALLBACK = {"record_calls": False, "require_consent": False, "retention_days": 0}


def get_compliance_config(account_id: int | None) -> dict:
    """Compliance settings for this tenant, defaulting to the safe values.

    Exists because the agent recorded every call unconditionally while the
    dashboard's record_calls toggle sat at False — the control existed and
    nothing honoured it (357 recordings were stored under a False flag).
    A DB failure returns the fallback, i.e. recording OFF, so an outage can
    never be the reason a call is recorded without the operator enabling it.
    """
    cached = _compliance_cache.get(account_id)
    now = time.monotonic()
    if cached is not None and now - cached[0] < _COMPLIANCE_CACHE_TTL_S:
        return cached[1]
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = 'compliance.config' AND account_id = ?",
            (account_id,),
        ).fetchone()
        cfg = dict(_COMPLIANCE_FALLBACK)
        if row and row["value"]:
            try:
                cfg.update(json.loads(row["value"]) or {})
            except ValueError:
                pass
    except psycopg.Error:
        logger.exception("could not read compliance config for account %s", account_id)
        return dict(_COMPLIANCE_FALLBACK)
    finally:
        conn.close()
    _compliance_cache[account_id] = (now, cfg)
    return cfg


def _normalize_sip_number(number: str) -> str:
    """Canonical phone_numbers.number shape — mirrors server/calls_db.py's
    _normalize_sip_number (and orchestrator/db.py's copy). This only has to
    match on lookup, not write."""
    digits = "".join(c for c in (number or "") if c.isdigit())
    if not digits:
        return (number or "").strip()
    if len(digits) == 10:
        digits = "91" + digits
    elif digits.startswith("0") and len(digits) == 11:
        digits = "91" + digits[1:]
    return "+" + digits


# Same per-process TTL cache as the agent-config/KB ones above, and for a
# sharper reason: this lookup sits in the inbound critical path, between the
# caller joining and the greeting, and dbconn.connect() opens a fresh
# connection every call. Measured uncached at 4.67s cold / 1.73s warm-ish
# against the real DB, which would have handed back everything the prewarm
# saves and then some. Warmed by prewarm_caches() so a real call never pays it.
_phone_number_cache: dict[str, tuple[float, dict | None]] = {}
_PHONE_NUMBER_CACHE_TTL_S = 600.0


def get_phone_number_by_number(number: str) -> dict | None:
    """account_id + agent_id for a registered inbound number.

    Unscoped by design: on an inbound call the dialled number is the only
    thing identifying the tenant. Needed because one LiveKit inbound trunk
    pools every tenant's numbers and a SIP dispatch rule cannot filter on
    the dialled number (its inbound_numbers field matches the CALLER), so
    the rule can only stamp one static agent_id into room metadata. The
    dialled number arrives instead as the SIP participant's
    sip.trunkPhoneNumber attribute, and this resolves it to the tenant that
    actually owns it.
    """
    key = _normalize_sip_number(number)
    cached = _phone_number_cache.get(key)
    now = time.monotonic()
    if cached is not None and now - cached[0] < _PHONE_NUMBER_CACHE_TTL_S:
        return cached[1]
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT account_id, agent_id FROM phone_numbers WHERE number = ?",
            (key,),
        ).fetchone()
        result = dict(row) if row else None
    except psycopg.Error:
        # Never cache a query failure — same reasoning as get_agent_config.
        return None
    finally:
        conn.close()
    _phone_number_cache[key] = (now, result)
    return result


def get_webhook_url() -> str | None:
    """URL of the connected CRM webhook integration, if any."""
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT config_json FROM integrations WHERE key = 'webhook' AND status = 'connected'"
        ).fetchone()
        if row is None:
            return None
        return json.loads(row["config_json"] or "{}").get("url") or None
    except psycopg.Error:
        return None
    finally:
        conn.close()


# Native appointment-booking (replaces Google Calendar/Cal.com entirely).
# Duplicates the SQL logic in server/calls_db.py's equivalents rather than
# importing them — this package can't import server/ (see module docstring).
_AVAILABILITY_DEFAULTS = {
    "timezone": "Asia/Kolkata",
    "slot_minutes": 30,
    "hours": {
        "Mon": {"open": "10:00", "close": "19:00"},
        "Tue": {"open": "10:00", "close": "19:00"},
        "Wed": {"open": "10:00", "close": "19:00"},
        "Thu": {"open": "10:00", "close": "19:00"},
        "Fri": {"open": "10:00", "close": "19:00"},
        "Sat": {"open": "10:00", "close": "19:00"},
        "Sun": None,
    },
    "blackout_dates": [],
}
_DAY_ABBR = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def _hhmm_to_minutes(t: str) -> int:
    h, m = t.split(":")
    return int(h) * 60 + int(m)


def get_availability_config(account_id: int | None) -> dict:
    if account_id is None:
        return dict(_AVAILABILITY_DEFAULTS)
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT value FROM settings WHERE account_id = ? AND key = 'availability.config'",
            (account_id,),
        ).fetchone()
        cfg = dict(_AVAILABILITY_DEFAULTS)
        if row and row["value"]:
            stored = json.loads(row["value"])
            if isinstance(stored, dict):
                cfg.update({k: v for k, v in stored.items() if k in _AVAILABILITY_DEFAULTS})
        return cfg
    except psycopg.Error:
        return dict(_AVAILABILITY_DEFAULTS)
    finally:
        conn.close()


def _appt_slot_conflict(conn, account_id: int, appt_date: str, start_time: str, duration_minutes: int) -> bool:
    rows = conn.execute(
        "SELECT start_time, duration_minutes FROM appointments "
        "WHERE account_id = ? AND appt_date = ? AND status = 'confirmed'",
        (account_id, appt_date),
    ).fetchall()
    new_start = _hhmm_to_minutes(start_time)
    new_end = new_start + duration_minutes
    for r in rows:
        s = _hhmm_to_minutes(r["start_time"])
        e = s + r["duration_minutes"]
        if new_start < e and new_end > s:
            return True
    return False


def check_appointment_availability(account_id: int | None, date: str, duration_minutes: int) -> list[str] | None:
    """Open HH:MM slots for `date` against the account's availability config +
    existing confirmed bookings. None only on a genuine DB error, so the tool
    degrades gracefully — matches the old _calendar_check contract, except
    the "no calendar connected" case no longer exists (a native calendar
    always exists once this account has any config, default or not)."""
    if account_id is None:
        # No real account to check confirmed bookings against — reporting
        # slots as free here would be a lie (the WHERE account_id = ? filter
        # never matches NULL, so booked slots would silently look open).
        return None
    conn = dbconn.connect()
    try:
        cfg = get_availability_config(account_id)
        weekday = _DAY_ABBR[datetime.date.fromisoformat(date).weekday()]
        if date in (cfg.get("blackout_dates") or []):
            return []
        hours = (cfg.get("hours") or {}).get(weekday)
        if not hours:
            return []
        slot_minutes = int(cfg.get("slot_minutes", 30))
        open_m, close_m = _hhmm_to_minutes(hours["open"]), _hhmm_to_minutes(hours["close"])
        now = datetime.datetime.now(ZoneInfo(cfg.get("timezone", "Asia/Kolkata")))
        is_today = date == now.date().isoformat()
        now_minutes = now.hour * 60 + now.minute
        slots: list[str] = []
        cursor = open_m
        while cursor + duration_minutes <= close_m:
            hhmm = f"{cursor // 60:02d}:{cursor % 60:02d}"
            if not (is_today and cursor <= now_minutes) and not _appt_slot_conflict(conn, account_id, date, hhmm, duration_minutes):
                slots.append(hhmm)
            cursor += slot_minutes
        return slots
    except psycopg.Error:
        return None
    finally:
        conn.close()


def book_native_appointment(
    account_id: int | None,
    agent_id: int | None,
    date: str,
    time: str,
    duration_minutes: int,
    name: str,
    phone: str,
    purpose: str,
) -> dict | None:
    """{"ok": True/False, ...} on success/handled-failure, None only on a
    genuine DB error — matches the old _calendar_book contract."""
    if account_id is None:
        return None
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute("SELECT pg_advisory_xact_lock(hashtext(?))", (f"appt:{account_id}:{date}",))
            if _appt_slot_conflict(conn, account_id, date, time, duration_minutes):
                return {"ok": False, "error": "slot no longer available"}
            conn.execute(
                "INSERT INTO appointments (account_id, agent_id, call_id, contact_name, contact_phone, "
                "contact_email, purpose, appt_date, start_time, duration_minutes, status, source) "
                "VALUES (?, ?, NULL, ?, ?, '', ?, ?, ?, ?, 'confirmed', 'agent')",
                (account_id, agent_id, name, phone, purpose, date, time, duration_minutes),
            )
            return {"ok": True}
    except psycopg.Error:
        return None
    finally:
        conn.close()


def get_delivery_integrations(account_id: int | None) -> list[dict]:
    """This tenant's connected lead-delivery integrations (Slack/Sheets/
    WhatsApp/CRM/ArthaLeads), account-scoped, as [{key, config}]. Empty on any
    error — integration delivery is best-effort and must never break a live
    call."""
    if account_id is None:
        return []
    conn = dbconn.connect()
    try:
        rows = conn.execute(
            "SELECT key, config_json FROM integrations "
            "WHERE account_id = ? AND status = 'connected' "
            "AND key IN ('webhook', 'slack', 'whatsapp', 'sheets', 'arthaleads')",
            (account_id,),
        ).fetchall()
        return [{"key": r["key"], "config": json.loads(r["config_json"] or "{}")} for r in rows]
    except psycopg.Error:
        return []
    finally:
        conn.close()


_NOW = "(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))"


def touch_integration_sync(account_id: int | None, key: str) -> None:
    """Stamp last_sync = now and clear any stale last_error after a
    successful live-call delivery. Best-effort — a status-tracking hiccup
    must never surface to the caller."""
    if account_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                f"UPDATE integrations SET last_sync = {_NOW}, last_error = NULL "
                "WHERE key = ? AND account_id = ?",
                (key, account_id),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist integration sync timestamp")
    finally:
        conn.close()


def mark_integration_error(account_id: int | None, key: str, message: str) -> None:
    """Record why the last live-call delivery to this integration failed, so
    it's visible on the Integrations card (e.g. "invalid token — reconnect")
    without disturbing the saved config."""
    if account_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "UPDATE integrations SET last_error = ? WHERE key = ? AND account_id = ?",
                (message[:500], key, account_id),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist integration error")
    finally:
        conn.close()


def save_call(record: dict) -> int | None:
    """Persist one completed call. Returns the new call's id (or None on
    failure) — used to attach a per-call ArthaLeads delivery outcome after
    the fact. `record` keys:

    room_name, visitor_identity, started_at, ended_at, duration_seconds,
    reply_language, voice (the exact voice string this call used, for
    per-voice-tier credit billing — see server/calls_db.py's voice_tier()),
    transcript (list of {role, text}), call_type
    ('phone'/'widget'/'browser'), direction ('inbound'/'outbound', phone
    calls only — see agent/main.py's _call_context_from_job), site_id (for
    'widget' calls), agent_id, account_id (which tenant this call belongs
    to), and optionally
    name/phone/email/budget/location/timeline/site_visit (dict with
    property_id/date/time) — matching the keys tools.py's log_lead and
    book_appointment write into the shared lead_data dict — or
    company/use_case/team_size, matching capture_platform_lead's keys for
    the platform-assistant persona.
    """
    conn = dbconn.connect()
    try:
        with conn:
            cur = conn.execute(
                """
                INSERT INTO calls (
                    room_name, visitor_identity, started_at, ended_at,
                    duration_seconds, reply_language, voice, model, lead_name, lead_phone,
                    lead_email, lead_budget, lead_location, lead_timeline, lead_company,
                    lead_use_case, lead_team_size, site_visit_json,
                    transcript_json, call_type, direction, site_id, agent_id, account_id,
                    extracted_data, latency_metrics_json
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    record["room_name"],
                    record.get("visitor_identity"),
                    record["started_at"],
                    record["ended_at"],
                    record["duration_seconds"],
                    record.get("reply_language"),
                    record.get("voice"),
                    record.get("model"),
                    record.get("name"),
                    record.get("phone"),
                    record.get("email"),
                    record.get("budget"),
                    record.get("location"),
                    record.get("timeline"),
                    record.get("company"),
                    record.get("use_case"),
                    record.get("team_size"),
                    json.dumps(record["site_visit"]) if record.get("site_visit") else None,
                    json.dumps(record["transcript"], ensure_ascii=False),
                    record.get("call_type") or "browser",
                    record.get("direction"),
                    record.get("site_id"),
                    record.get("agent_id"),
                    record.get("account_id"),
                    json.dumps(record["extracted_data"], ensure_ascii=False)
                    if record.get("extracted_data")
                    else "",
                    json.dumps(record.get("latency_metrics") or {}, ensure_ascii=False),
                ),
            )
            return cur.lastrowid
    finally:
        conn.close()


def set_call_arthaleads_status(call_id: int | None, status: str, error: str | None = None) -> None:
    """Records this specific call's ArthaLeads delivery outcome — separate
    from the integration-level last_sync/last_error, which only reflect the
    most recent attempt across every call. Best-effort: a status-tracking
    hiccup must never surface to the caller or disturb call teardown."""
    if call_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                f"UPDATE calls SET arthaleads_status = ?, arthaleads_synced_at = {_NOW}, "
                "arthaleads_error = ? WHERE id = ?",
                (status, error, call_id),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist ArthaLeads status")
    finally:
        conn.close()


def set_call_extracted_data(call_id: int | None, extracted: dict) -> None:
    """Attaches post-call extracted fields after save_call's INSERT.

    Same save-now-update-later shape as set_call_recording below. Exists so
    the post-call LLM pass can run AFTER the durable record is written
    instead of gating it: that analysis is an optional enrichment, but it
    used to sit in front of save_call in main.py's shutdown callback, so a
    slow or hung OpenAI request took the transcript, the recording and the
    billing row down with it (observed live 2026-08-21 — a real 60s call
    left no row at all while shorter calls in the same window saved fine).
    Best-effort: a failure here must never disturb call teardown."""
    if call_id is None or not extracted:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "UPDATE calls SET extracted_data = ? WHERE id = ?",
                (json.dumps(extracted), call_id),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist post-call extracted data")
    finally:
        conn.close()


def set_call_recording(call_id: int | None, recording_key: str) -> None:
    """Attaches this call's R2 recording key after upload finishes — same
    save-now-update-later shape as set_call_arthaleads_status above, since
    the recording isn't ready until after save_call's initial INSERT.
    Best-effort: a failure here must never disturb call teardown."""
    if call_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "UPDATE calls SET recording_key = ? WHERE id = ?",
                (recording_key, call_id),
            )
    except Exception:
        # Best-effort, but never silent: swallowing this lost real data.
        # A recording uploaded fine to B2 on 2026-08-21 while this UPDATE
        # failed, so calls showed no recording even though the audio existed.
        # Catches Exception, not psycopg.Error: the connection pool raises
        # PoolTimeout, which is not a psycopg.Error and slipped past entirely.
        logger.exception("could not persist recording key")
    finally:
        conn.close()
