"""Local call-log storage.

Shares one Postgres database with server/calls_db.py (server owns agents,
knowledge_bases, kb_qa, integrations, etc.; this module owns `calls` and
writes completed-call rows, plus reads the tables it needs at call time).
Was SQLite through early development; moved to Postgres for the
durability/concurrency a sellable multi-tenant product needs — see
vistrow-voice-infrastructure-requirements.txt. dbconn.py (duplicated from
server/, since this package pulls in livekit-agents which isn't installed
in server's venv) is a thin shim that keeps every call site below in its
original sqlite3-flavored form (`?` placeholders, `with conn:` committing
without closing).
"""

import json

import psycopg

import dbconn

_SCHEMA = """
CREATE TABLE IF NOT EXISTS calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name TEXT NOT NULL,
    visitor_identity TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    duration_seconds REAL,
    reply_language TEXT,
    lead_name TEXT,
    lead_phone TEXT,
    lead_email TEXT,
    lead_budget TEXT,
    lead_location TEXT,
    lead_timeline TEXT,
    lead_company TEXT,
    lead_use_case TEXT,
    lead_team_size TEXT,
    site_visit_json TEXT,
    transcript_json TEXT NOT NULL,
    call_type TEXT DEFAULT 'browser',
    site_id INTEGER,
    agent_id INTEGER,
    account_id INTEGER,
    extracted_data TEXT DEFAULT ''
);

-- Mirrors server/calls_db.py — created here too so the agent works even if it
-- boots against a fresh DB before the backend has. Holds one rolling summary
-- per (agent, caller phone) for agents with memory enabled.
CREATE TABLE IF NOT EXISTS caller_memory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER,
    agent_id INTEGER,
    caller_phone TEXT NOT NULL,
    summary TEXT DEFAULT '',
    updated_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text,
    UNIQUE(agent_id, caller_phone)
);
"""


def init_db() -> None:
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(_SCHEMA)
            # Whichever of server/agent boots first creates the base table via
            # CREATE TABLE IF NOT EXISTS above (a no-op if it already exists) —
            # columns added after go-live still need an explicit migration to
            # land, regardless of boot order.
            for column in ("lead_company", "lead_use_case", "lead_team_size", "lead_email"):
                conn.execute(f"ALTER TABLE calls ADD COLUMN IF NOT EXISTS {column} TEXT")
            conn.execute("ALTER TABLE calls ADD COLUMN IF NOT EXISTS extracted_data TEXT DEFAULT ''")
    finally:
        conn.close()


def get_caller_memory(agent_id: int, caller_phone: str) -> str:
    """The rolling summary of prior calls with this caller for this agent,
    or '' if none / memory table absent. Only phone calls have a stable
    caller_phone, so web calls never hit this."""
    if not caller_phone:
        return ""
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT summary FROM caller_memory WHERE agent_id = ? AND caller_phone = ?",
            (agent_id, caller_phone),
        ).fetchone()
        return (row["summary"] or "") if row else ""
    except psycopg.Error:
        return ""
    finally:
        conn.close()


def save_caller_memory(account_id: int | None, agent_id: int, caller_phone: str, summary: str) -> None:
    """Upsert the rolling summary for (agent, caller). Best-effort — a failure
    here must never break call teardown."""
    if not (caller_phone and summary):
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "INSERT INTO caller_memory (account_id, agent_id, caller_phone, summary) "
                "VALUES (?, ?, ?, ?) "
                "ON CONFLICT (agent_id, caller_phone) DO UPDATE SET "
                "summary = EXCLUDED.summary, updated_at = (now() AT TIME ZONE 'utc')::text",
                (account_id, agent_id, caller_phone, summary),
            )
    except psycopg.Error:
        pass
    finally:
        conn.close()


def get_agent_config(agent_id: int | None = None) -> dict | None:
    """Dashboard-managed agent settings (server/calls_db.py owns the table).

    With `agent_id`, loads that specific agent — used by inbound phone calls,
    where the LiveKit dispatch rule for the dialed number names which agent
    handles it. Without it (an unrouted browser call, notably the public
    marketing site's /demo and /call), prefers whichever agent is flagged
    is_platform_demo — see server/calls_db.py update_agent — falling back to
    the first agent by id if none is flagged yet. Returns None when the
    table doesn't exist yet (dashboard API never ran) or the id isn't found,
    so callers fall back to the in-code defaults and the agent keeps working
    standalone.
    """
    conn = dbconn.connect()
    try:
        if agent_id is not None:
            row = conn.execute("SELECT * FROM agents WHERE id = ?", (agent_id,)).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM agents ORDER BY is_platform_demo DESC, id LIMIT 1"
            ).fetchone()
        return dict(row) if row else None
    except psycopg.Error:
        return None
    finally:
        conn.close()


def get_kb_content(kb_id: int, max_chars: int = 8000) -> str:
    """Knowledge-base text to append to the system prompt.

    Curated Q&A pairs (kb_qa, the operator-reviewed FAQ) come first so they
    always survive the char cap — they're the facts the operator explicitly
    signed off on — followed by raw sources with whatever budget remains.

    Prompt-stuffing rather than embeddings — right-sized while KBs are a few
    brochures/price sheets; swap for retrieval once sources outgrow this cap.
    """
    conn = dbconn.connect()
    try:
        parts: list[str] = []
        try:
            qa_rows = conn.execute(
                "SELECT question, answer FROM kb_qa WHERE kb_id = ? ORDER BY position, id",
                (kb_id,),
            ).fetchall()
        except psycopg.Error:
            # kb_qa table doesn't exist yet (dashboard API predates KB 2.0).
            qa_rows = []
        if qa_rows:
            faq = "\n\n".join(f"Q: {r['question']}\nA: {r['answer']}" for r in qa_rows)
            parts.append("## Approved answers (quote these when the question matches)\n" + faq)
        rows = conn.execute(
            "SELECT name, content FROM knowledge_sources WHERE kb_id = ? ORDER BY id",
            (kb_id,),
        ).fetchall()
        parts.extend(f"## {r['name']}\n{r['content']}" for r in rows)
        return "\n\n".join(parts)[:max_chars]
    except psycopg.Error:
        return ""
    finally:
        conn.close()


def is_kb_strict(kb_id: int) -> bool:
    """Whether the operator turned strict mode on for this KB (default yes)."""
    conn = dbconn.connect()
    try:
        row = conn.execute("SELECT strict FROM knowledge_bases WHERE id = ?", (kb_id,)).fetchone()
        return bool(row["strict"]) if row is not None else True
    except psycopg.Error:
        # strict column predates KB 2.0 — treat as strict, the safe default.
        return True
    finally:
        conn.close()


def get_webhook_url() -> str | None:
    """URL of the connected CRM webhook integration, if any."""
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT config_json FROM integrations WHERE key = 'webhook' AND status = 'connected'"
        ).fetchone()
        if row is None:
            return None
        return json.loads(row["config_json"] or "{}").get("url") or None
    except psycopg.Error:
        return None
    finally:
        conn.close()


def get_gcal_config(account_id: int | None) -> dict | None:
    """The connected Google Calendar integration's config for this tenant, or
    None if nothing is connected. Two shapes depending on how the tenant
    connected: {"mode":"oauth","access_token",...} for the one-click OAuth
    connect (server/token_api.py's gcal_oauth_callback), or {"url":...} for
    the older Apps Script web-app bridge. Account-scoped; None on any error
    so a booking tool degrades to a graceful 'I'll have the team confirm'
    instead of crashing the call."""
    if account_id is None:
        return None
    conn = dbconn.connect()
    try:
        row = conn.execute(
            "SELECT config_json FROM integrations "
            "WHERE account_id = ? AND key = 'gcal' AND status = 'connected'",
            (account_id,),
        ).fetchone()
        if row is None:
            return None
        cfg = json.loads(row["config_json"] or "{}")
        return cfg or None
    except psycopg.Error:
        return None
    finally:
        conn.close()


def update_gcal_access_token(account_id: int, access_token: str, expires_at: int) -> None:
    """Persist a refreshed OAuth access token so the next call reuses it
    instead of refreshing again. Read-modify-write to preserve the other
    stored fields (refresh_token, connected_email)."""
    conn = dbconn.connect()
    try:
        with conn:
            row = conn.execute(
                "SELECT config_json FROM integrations WHERE account_id = ? AND key = 'gcal'",
                (account_id,),
            ).fetchone()
            cfg = json.loads(row["config_json"] or "{}") if row else {}
            cfg["access_token"] = access_token
            cfg["token_expires_at"] = expires_at
            conn.execute(
                "UPDATE integrations SET config_json = ? WHERE account_id = ? AND key = 'gcal'",
                (json.dumps(cfg), account_id),
            )
    except psycopg.Error:
        pass
    finally:
        conn.close()


def get_delivery_integrations(account_id: int | None) -> list[dict]:
    """This tenant's connected lead-delivery integrations (Slack/Sheets/
    WhatsApp/CRM/ArthaLeads), account-scoped, as [{key, config}]. Empty on any
    error — integration delivery is best-effort and must never break a live
    call."""
    if account_id is None:
        return []
    conn = dbconn.connect()
    try:
        rows = conn.execute(
            "SELECT key, config_json FROM integrations "
            "WHERE account_id = ? AND status = 'connected' "
            "AND key IN ('webhook', 'slack', 'whatsapp', 'sheets', 'arthaleads')",
            (account_id,),
        ).fetchall()
        return [{"key": r["key"], "config": json.loads(r["config_json"] or "{}")} for r in rows]
    except psycopg.Error:
        return []
    finally:
        conn.close()


_NOW = "(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))"


def touch_integration_sync(account_id: int | None, key: str) -> None:
    """Stamp last_sync = now and clear any stale last_error after a
    successful live-call delivery. Best-effort — a status-tracking hiccup
    must never surface to the caller."""
    if account_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                f"UPDATE integrations SET last_sync = {_NOW}, last_error = NULL "
                "WHERE key = ? AND account_id = ?",
                (key, account_id),
            )
    except psycopg.Error:
        pass
    finally:
        conn.close()


def mark_integration_error(account_id: int | None, key: str, message: str) -> None:
    """Record why the last live-call delivery to this integration failed, so
    it's visible on the Integrations card (e.g. "invalid token — reconnect")
    without disturbing the saved config."""
    if account_id is None:
        return
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                "UPDATE integrations SET last_error = ? WHERE key = ? AND account_id = ?",
                (message[:500], key, account_id),
            )
    except psycopg.Error:
        pass
    finally:
        conn.close()


def save_call(record: dict) -> None:
    """Persist one completed call. `record` keys:

    room_name, visitor_identity, started_at, ended_at, duration_seconds,
    reply_language, voice (the exact voice string this call used, for
    per-voice-tier credit billing — see server/calls_db.py's voice_tier()),
    transcript (list of {role, text}), call_type
    ('phone'/'widget'/'browser'), site_id (for 'widget' calls), agent_id,
    account_id (which tenant this call belongs to), and optionally
    name/phone/email/budget/location/timeline/site_visit (dict with
    property_id/date/time) — matching the keys tools.py's log_lead and
    book_appointment write into the shared lead_data dict — or
    company/use_case/team_size, matching capture_platform_lead's keys for
    the platform-assistant persona.
    """
    conn = dbconn.connect()
    try:
        with conn:
            conn.execute(
                """
                INSERT INTO calls (
                    room_name, visitor_identity, started_at, ended_at,
                    duration_seconds, reply_language, voice, lead_name, lead_phone,
                    lead_email, lead_budget, lead_location, lead_timeline, lead_company,
                    lead_use_case, lead_team_size, site_visit_json,
                    transcript_json, call_type, site_id, agent_id, account_id,
                    extracted_data
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    record["room_name"],
                    record.get("visitor_identity"),
                    record["started_at"],
                    record["ended_at"],
                    record["duration_seconds"],
                    record.get("reply_language"),
                    record.get("voice"),
                    record.get("name"),
                    record.get("phone"),
                    record.get("email"),
                    record.get("budget"),
                    record.get("location"),
                    record.get("timeline"),
                    record.get("company"),
                    record.get("use_case"),
                    record.get("team_size"),
                    json.dumps(record["site_visit"]) if record.get("site_visit") else None,
                    json.dumps(record["transcript"], ensure_ascii=False),
                    record.get("call_type") or "browser",
                    record.get("site_id"),
                    record.get("agent_id"),
                    record.get("account_id"),
                    json.dumps(record["extracted_data"], ensure_ascii=False)
                    if record.get("extracted_data")
                    else "",
                ),
            )
    finally:
        conn.close()
